/*
**
** The C code is generated by [ATS/Postiats-0-4-1]
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
$(PATSHOME)/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
$(PATSHOME)/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
$(PATSHOME)/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
$(PATSHOME)/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
$(PATSHOME)/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
$(PATSHOME)/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_g0int2int_int_int)
ATSdyncst_mac(atspre_g0int_eq_int)
ATSdyncst_mac(atspre_land_int_int)
ATSdyncst_mac(atspre_g1int_add_int)
ATSdyncst_extfun(build_057_bats_modules_057_arith_057_src_057_lib_056_sats__low_byte, (atstkind_t0ype(atstype_int)), atstkind_t0ype(atstype_int)) ;
ATSdyncst_mac(atspre_char2int0)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
build_057_bats_modules_057_arith_057_src_057_lib_056_sats__low_byte(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

ATSstatic()
atstkind_t0ype(atstype_int)
bit_1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__2(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__2__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
build_057_bats_modules_057_arith_057_src_057_lib_056_sats__byte_of_char(atstkind_t0ype(atstype_char)) ;
#endif // end of [QUALIFIED]

/*
build/bats_modules/arith/src/lib.dats: 748(line=79, offs=19) -- 985(line=85, offs=4)
*/
/*
local: 
global: low_byte$0$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_int)
build_057_bats_modules_057_arith_057_src_057_lib_056_sats__low_byte(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp8, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp9, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp10, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp11, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp12, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp13, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp14, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp15, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp16, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp17, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp18, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp19, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp20, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp21, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/arith/src/lib.dats: 740(line=79, offs=11) -- 985(line=85, offs=4)
*/
ATSINSflab(__patsflab_low_byte):
/*
emit_instr: loc0 = build/bats_modules/arith/src/lib.dats: 754(line=79, offs=25) -- 985(line=85, offs=4)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = build/bats_modules/arith/src/lib.dats: 879(line=83, offs=3) -- 890(line=83, offs=14)
*/
ATSINSmove(tmp14, bit_1(arg0, ATSPMVi0nt(128))) ;

/*
emit_instr: loc0 = build/bats_modules/arith/src/lib.dats: 893(line=83, offs=17) -- 903(line=83, offs=27)
*/
ATSINSmove(tmp15, bit_1(arg0, ATSPMVi0nt(64))) ;

/*
emit_instr: loc0 = build/bats_modules/arith/src/lib.dats: 879(line=83, offs=3) -- 903(line=83, offs=27)
*/
ATSINSmove(tmp13, atspre_g1int_add_int(tmp14, tmp15)) ;

/*
emit_instr: loc0 = build/bats_modules/arith/src/lib.dats: 906(line=83, offs=30) -- 916(line=83, offs=40)
*/
ATSINSmove(tmp16, bit_1(arg0, ATSPMVi0nt(32))) ;

/*
emit_instr: loc0 = build/bats_modules/arith/src/lib.dats: 879(line=83, offs=3) -- 916(line=83, offs=40)
*/
ATSINSmove(tmp12, atspre_g1int_add_int(tmp13, tmp16)) ;

/*
emit_instr: loc0 = build/bats_modules/arith/src/lib.dats: 919(line=83, offs=43) -- 929(line=83, offs=53)
*/
ATSINSmove(tmp17, bit_1(arg0, ATSPMVi0nt(16))) ;

/*
emit_instr: loc0 = build/bats_modules/arith/src/lib.dats: 879(line=83, offs=3) -- 929(line=83, offs=53)
*/
ATSINSmove(tmp11, atspre_g1int_add_int(tmp12, tmp17)) ;

/*
emit_instr: loc0 = build/bats_modules/arith/src/lib.dats: 936(line=84, offs=7) -- 945(line=84, offs=16)
*/
ATSINSmove(tmp18, bit_1(arg0, ATSPMVi0nt(8))) ;

/*
emit_instr: loc0 = build/bats_modules/arith/src/lib.dats: 879(line=83, offs=3) -- 945(line=84, offs=16)
*/
ATSINSmove(tmp10, atspre_g1int_add_int(tmp11, tmp18)) ;

/*
emit_instr: loc0 = build/bats_modules/arith/src/lib.dats: 948(line=84, offs=19) -- 957(line=84, offs=28)
*/
ATSINSmove(tmp19, bit_1(arg0, ATSPMVi0nt(4))) ;

/*
emit_instr: loc0 = build/bats_modules/arith/src/lib.dats: 879(line=83, offs=3) -- 957(line=84, offs=28)
*/
ATSINSmove(tmp9, atspre_g1int_add_int(tmp10, tmp19)) ;

/*
emit_instr: loc0 = build/bats_modules/arith/src/lib.dats: 960(line=84, offs=31) -- 969(line=84, offs=40)
*/
ATSINSmove(tmp20, bit_1(arg0, ATSPMVi0nt(2))) ;

/*
emit_instr: loc0 = build/bats_modules/arith/src/lib.dats: 879(line=83, offs=3) -- 969(line=84, offs=40)
*/
ATSINSmove(tmp8, atspre_g1int_add_int(tmp9, tmp20)) ;

/*
emit_instr: loc0 = build/bats_modules/arith/src/lib.dats: 972(line=84, offs=43) -- 981(line=84, offs=52)
*/
ATSINSmove(tmp21, bit_1(arg0, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = build/bats_modules/arith/src/lib.dats: 879(line=83, offs=3) -- 981(line=84, offs=52)
*/
ATSINSmove(tmpret0, atspre_g1int_add_int(tmp8, tmp21)) ;

/*
emit_instr: loc0 = build/bats_modules/arith/src/lib.dats: 754(line=79, offs=25) -- 985(line=85, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [build_057_bats_modules_057_arith_057_src_057_lib_056_sats__low_byte] */

/*
build/bats_modules/arith/src/lib.dats: 763(line=80, offs=6) -- 873(line=81, offs=44)
*/
/*
local: 
global: bit_1$0(level=1)
local: 
global: 
*/
ATSstatic()
atstkind_t0ype(atstype_int)
bit_1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp7, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/arith/src/lib.dats: 763(line=80, offs=6) -- 873(line=81, offs=44)
*/
ATSINSflab(__patsflab_bit_1):
/*
emit_instr: loc0 = build/bats_modules/arith/src/lib.dats: 837(line=81, offs=8) -- 855(line=81, offs=26)
*/
ATSINSmove(tmp7, atspre_land_int_int(arg0, arg1)) ;

/*
emit_instr: loc0 = build/bats_modules/arith/src/lib.dats: 837(line=81, offs=8) -- 859(line=81, offs=30)
*/
ATSINSmove(tmp2, ATSLIB_056_prelude__eq_g0int_int__2__1(tmp7, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = build/bats_modules/arith/src/lib.dats: 834(line=81, offs=5) -- 873(line=81, offs=44)
*/
ATSif(
tmp2
) ATSthen() {
/*
emit_instr: loc0 = build/bats_modules/arith/src/lib.dats: 865(line=81, offs=36) -- 866(line=81, offs=37)
*/
ATSINSmove(tmpret1, ATSPMVi0nt(0)) ;
} ATSelse() {
/*
emit_instr: loc0 = build/bats_modules/arith/src/lib.dats: 872(line=81, offs=43) -- 873(line=81, offs=44)
*/
ATSINSmove(tmpret1, arg1) ;
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret1) ;
} /* end of [bit_1] */

#if(0)
/*
$(PATSHOME)/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$2$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4659)
tmparg = S2Evar(tk(4659))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__2(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp4, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp4, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4659))>)(arg1)) ;

/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret3, PMVtmpltcst(g0int_eq<S2Evar(tk(4659))>)(arg0, tmp4)) ;

ATSfunbody_end()
ATSreturn(tmpret3) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__2] */
#endif // end of [TEMPLATE]

/*
$(PATSHOME)/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$2$1(level=2)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4659)
tmparg = S2Evar(tk(4659))
tmpsub = Some(tk(4659) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__2__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp4__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp4__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret3__1, atspre_g0int_eq_int(arg0, tmp4__1)) ;

ATSfunbody_end()
ATSreturn(tmpret3__1) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__2__1] */

/*
build/bats_modules/arith/src/lib.dats: 1011(line=89, offs=23) -- 1039(line=89, offs=51)
*/
/*
local: 
global: byte_of_char$7$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_int)
build_057_bats_modules_057_arith_057_src_057_lib_056_sats__byte_of_char(atstkind_t0ype(atstype_char) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret22, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp23, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/arith/src/lib.dats: 999(line=89, offs=11) -- 1039(line=89, offs=51)
*/
ATSINSflab(__patsflab_byte_of_char):
/*
emit_instr: loc0 = build/bats_modules/arith/src/lib.dats: 1026(line=89, offs=38) -- 1037(line=89, offs=49)
*/
ATSINSmove(tmp23, atspre_char2int0(arg0)) ;

/*
emit_instr: loc0 = build/bats_modules/arith/src/lib.dats: 1017(line=89, offs=29) -- 1039(line=89, offs=51)
*/
ATSINSmove(tmpret22, build_057_bats_modules_057_arith_057_src_057_lib_056_sats__low_byte(tmp23)) ;

ATSfunbody_end()
ATSreturn(tmpret22) ;
} /* end of [build_057_bats_modules_057_arith_057_src_057_lib_056_sats__byte_of_char] */

/*
** for initialization(dynloading)
*/
ATSextern()
atsvoid_t0ype
build_057_bats_modules_057_arith_057_src_057_lib_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_ext(
build_057_bats_modules_057_arith_057_src_057_lib_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
build_057_bats_modules_057_arith_057_src_057_lib_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(build_057_bats_modules_057_arith_057_src_057_lib_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/* ****** ****** */

/* end-of-compilation-unit */
