/*
**
** The C code is generated by [ATS/Postiats-0-4-1]
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
$(PATSHOME)/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
$(PATSHOME)/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
$(PATSHOME)/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
$(PATSHOME)/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
$(PATSHOME)/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
$(PATSHOME)/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_0 ;
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_1 ;
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_2 ;
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_3 ;
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_4 ;
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_5 ;
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_6 ;
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstyvar_type(b) atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_7 ;
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_8 ;
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_9 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
#if(0)
#if(0)
ATSextern()
atstype_boxed
build_057_bats_modules_057_list_057_src_057_lib_056_sats__nil__0() ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstype_boxed
build_057_bats_modules_057_list_057_src_057_lib_056_sats__cons__1(atstyvar_type(a), atstype_boxed) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atsvoid_t0ype
build_057_bats_modules_057_list_057_src_057_lib_056_sats__free__2(atstype_boxed) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstatic()
atsvoid_t0ype
loop_3__3(atstype_boxed) ;
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
build_057_bats_modules_057_list_057_src_057_lib_056_sats__length__4(atsrefarg0_type(atstype_boxed)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstatic()
atstkind_t0ype(atstype_int)
loop_5__5(atsrefarg0_type(atstype_boxed), atstkind_t0ype(atstype_int)) ;
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
build_057_bats_modules_057_list_057_src_057_lib_056_sats__is_nil__6(atsrefarg0_type(atstype_boxed)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstype_boxed
build_057_bats_modules_057_list_057_src_057_lib_056_sats__reverse__7(atstype_boxed) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstatic()
atstype_boxed
loop_8__8(atstype_boxed, atstype_boxed) ;
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstyvar_type(a)
build_057_bats_modules_057_list_057_src_057_lib_056_sats__head__9(atsrefarg0_type(atstype_boxed)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstype_boxed
build_057_bats_modules_057_list_057_src_057_lib_056_sats__tail__10(atstype_boxed) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstype_boxed
build_057_bats_modules_057_list_057_src_057_lib_056_sats__map__11(atsrefarg0_type(atstype_boxed), atsrefarg1_type(atstyclo_top)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstatic()
atstype_boxed
loop_12__12(atsrefarg0_type(atstype_boxed), atsrefarg1_type(atstyclo_top)) ;
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstyvar_type(b)
build_057_bats_modules_057_list_057_src_057_lib_056_sats__foldl__13(atsrefarg0_type(atstype_boxed), atstyvar_type(b), atsrefarg1_type(atstyclo_top)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstatic()
atstyvar_type(b)
loop_14__14(atsrefarg0_type(atstype_boxed), atstyvar_type(b), atsrefarg1_type(atstyclo_top)) ;
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstype_boxed
build_057_bats_modules_057_list_057_src_057_lib_056_sats__append__15(atstype_boxed, atstype_boxed) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstatic()
atstype_boxed
loop_16__16(atstype_boxed, atstype_boxed) ;
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 830(line=36, offs=19) -- 848(line=36, offs=37)
*/
/*
local: 
global: nil$0$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8509)
tmparg = S2Evar(a(8509))
tmpsub = None()
*/
atstype_boxed
build_057_bats_modules_057_list_057_src_057_lib_056_sats__nil__0()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 826(line=36, offs=15) -- 848(line=36, offs=37)
*/
ATSINSflab(__patsflab_nil):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 835(line=36, offs=24) -- 848(line=36, offs=37)
*/

ATSINSmove_nil(tmpret0) ;

ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [build_057_bats_modules_057_list_057_src_057_lib_056_sats__nil__0] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 869(line=38, offs=20) -- 898(line=38, offs=49)
*/
/*
local: 
global: cons$1$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8510)
tmparg = S2Evar(a(8510))
tmpsub = None()
*/
atstype_boxed
build_057_bats_modules_057_list_057_src_057_lib_056_sats__cons__1(atstyvar_type(a) arg0, atstype_boxed arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret1, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 864(line=38, offs=15) -- 898(line=38, offs=49)
*/
ATSINSflab(__patsflab_cons):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 879(line=38, offs=30) -- 898(line=38, offs=49)
*/

/*
#LINCONSTATUS==0
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret1, postiats_tysum_0) ;
#if(0)
ATSINSstore_con1_tag(tmpret1, 1) ;
#endif
ATSINSstore_con1_ofs(tmpret1, postiats_tysum_0, atslab__0, arg0) ;
ATSINSstore_con1_ofs(tmpret1, postiats_tysum_0, atslab__1, arg1) ;
ATSINSmove_con1_end()
ATSfunbody_end()
ATSreturn(tmpret1) ;
} /* end of [build_057_bats_modules_057_list_057_src_057_lib_056_sats__cons__1] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 923(line=40, offs=24) -- 1088(line=46, offs=16)
*/
/*
local: 
global: free$2$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8512)
tmparg = S2Evar(a(8512))
tmpsub = None()
*/
atsvoid_t0ype
build_057_bats_modules_057_list_057_src_057_lib_056_sats__free__2(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret2) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 914(line=40, offs=15) -- 1088(line=46, offs=16)
*/
ATSINSflab(__patsflab_free):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 930(line=40, offs=31) -- 1088(line=46, offs=16)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1076(line=46, offs=4) -- 1083(line=46, offs=11)
*/
ATSINSmove_void(tmpret2, ATSfunclo_fun(PMVd2vfunlab(d2v=loop$4740(1), flab=loop_3$0(level=1)), (atstype_boxed), atsvoid_t0ype)(arg0)) ;

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 930(line=40, offs=31) -- 1088(line=46, offs=16)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret2) ;
} /* end of [build_057_bats_modules_057_list_057_src_057_lib_056_sats__free__2] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 940(line=41, offs=7) -- 1072(line=45, offs=39)
*/
/*
local: loop_3$0(level=1)
global: loop_3$0(level=1)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
loop_3__3(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstype_boxed) ;
// ATStmpdec_void(tmpret3) ;
ATStmpdec(tmp5, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 940(line=41, offs=7) -- 1072(line=45, offs=39)
*/
ATSINSflab(__patsflab_loop_3):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 995(line=43, offs=5) -- 1072(line=45, offs=39)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1013(line=44, offs=7) -- 1027(line=44, offs=21)
*/
ATSINSlab(__atstmplab0):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 964(line=42, offs=6) -- 966(line=42, offs=8)
*/
ATSifthen(ATSCKptriscons(arg0)) { ATSINSgoto(__atstmplab3) ; } ;
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1027(line=44, offs=21) -- 1027(line=44, offs=21)
*/
ATSINSlab(__atstmplab1):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1031(line=44, offs=25) -- 1033(line=44, offs=27)
*/
ATSINSmove_void(tmpret3, ATSPMVempty()) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1040(line=45, offs=7) -- 1060(line=45, offs=27)
*/
ATSINSlab(__atstmplab2):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 964(line=42, offs=6) -- 966(line=42, offs=8)
*/
#if(0)
ATSifthen(ATSCKptrisnull(arg0)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1060(line=45, offs=27) -- 1060(line=45, offs=27)
*/
ATSINSlab(__atstmplab3):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1057(line=45, offs=24) -- 1059(line=45, offs=26)
*/
ATSINSmove(tmp5, ATSSELcon(arg0, postiats_tysum_1, atslab__1)) ;
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1040(line=45, offs=7) -- 1072(line=45, offs=39)
*/
ATSINSfreecon(arg0) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1064(line=45, offs=31) -- 1071(line=45, offs=38)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, tmp5) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSfgoto(__patsflab_loop_3) ;
ATStailcal_end()

ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn_void(tmpret3) ;
} /* end of [loop_3__3] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 1274(line=58, offs=26) -- 1469(line=64, offs=19)
*/
/*
local: 
global: length$4$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8519)
tmparg = S2Evar(a(8519))
tmpsub = None()
*/
atstkind_t0ype(atstype_int)
build_057_bats_modules_057_list_057_src_057_lib_056_sats__length__4(atsrefarg0_type(atstype_boxed) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret6, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1263(line=58, offs=15) -- 1469(line=64, offs=19)
*/
ATSINSflab(__patsflab_length):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1281(line=58, offs=33) -- 1469(line=64, offs=19)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1454(line=64, offs=4) -- 1465(line=64, offs=15)
*/
ATSINSmove(tmpret6, ATSfunclo_fun(PMVd2vfunlab(d2v=loop$4744(1), flab=loop_5$0(level=1)), (atsrefarg0_type(atstype_boxed), atstkind_t0ype(atstype_int)), atstkind_t0ype(atstype_int))(ATSPMVrefarg0(arg0), ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1281(line=58, offs=33) -- 1469(line=64, offs=19)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret6) ;
} /* end of [build_057_bats_modules_057_list_057_src_057_lib_056_sats__length__4] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 1291(line=59, offs=7) -- 1450(line=63, offs=45)
*/
/*
local: loop_5$0(level=1)
global: loop_5$0(level=1)
local: 
global: 
*/
ATSstatic()
atstkind_t0ype(atstype_int)
loop_5__5(atsrefarg0_type(atstype_boxed) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atsrefarg0_type(atstype_boxed)) ;
ATStmpdec(apy1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmpret7, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp9, atstype_boxed) ;
ATStmpdec(tmp10, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1291(line=59, offs=7) -- 1450(line=63, offs=45)
*/
ATSINSflab(__patsflab_loop_5):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1369(line=61, offs=5) -- 1450(line=63, offs=45)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1387(line=62, offs=7) -- 1400(line=62, offs=20)
*/
ATSINSlab(__atstmplab4):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1322(line=60, offs=6) -- 1324(line=60, offs=8)
*/
ATSifthen(ATSCKptriscons(arg0)) { ATSINSgoto(__atstmplab7) ; } ;
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1400(line=62, offs=20) -- 1400(line=62, offs=20)
*/
ATSINSlab(__atstmplab5):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1404(line=62, offs=24) -- 1405(line=62, offs=25)
*/
ATSINSmove(tmpret7, arg1) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1412(line=63, offs=7) -- 1431(line=63, offs=26)
*/
ATSINSlab(__atstmplab6):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1322(line=60, offs=6) -- 1324(line=60, offs=8)
*/
#if(0)
ATSifthen(ATSCKptrisnull(arg0)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1431(line=63, offs=26) -- 1431(line=63, offs=26)
*/
ATSINSlab(__atstmplab7):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1428(line=63, offs=23) -- 1430(line=63, offs=25)
*/
ATSINSmove(tmp9, ATSSELcon(arg0, postiats_tysum_2, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1444(line=63, offs=39) -- 1449(line=63, offs=44)
*/
ATSINSmove(tmp10, PMVtmpltcst(g1int_add<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1435(line=63, offs=30) -- 1450(line=63, offs=45)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, ATSPMVrefarg0(tmp9)) ;
ATSINSmove_tlcal(apy1, tmp10) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSfgoto(__patsflab_loop_5) ;
ATStailcal_end()

ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret7) ;
} /* end of [loop_5__5] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 1492(line=66, offs=22) -- 1570(line=69, offs=32)
*/
/*
local: 
global: is_nil$6$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8527)
tmparg = S2Evar(a(8527))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
build_057_bats_modules_057_list_057_src_057_lib_056_sats__is_nil__6(atsrefarg0_type(atstype_boxed) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret11, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1485(line=66, offs=15) -- 1570(line=69, offs=32)
*/
ATSINSflab(__patsflab_is_nil):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1501(line=67, offs=3) -- 1570(line=69, offs=32)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1517(line=68, offs=5) -- 1530(line=68, offs=18)
*/
ATSINSlab(__atstmplab8):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1493(line=66, offs=23) -- 1495(line=66, offs=25)
*/
ATSifthen(ATSCKptriscons(arg0)) { ATSINSgoto(__atstmplab11) ; } ;
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1530(line=68, offs=18) -- 1530(line=68, offs=18)
*/
ATSINSlab(__atstmplab9):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1534(line=68, offs=22) -- 1538(line=68, offs=26)
*/
ATSINSmove(tmpret11, ATSPMVbool_true()) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1543(line=69, offs=5) -- 1561(line=69, offs=23)
*/
ATSINSlab(__atstmplab10):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1493(line=66, offs=23) -- 1495(line=66, offs=25)
*/
#if(0)
ATSifthen(ATSCKptrisnull(arg0)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1561(line=69, offs=23) -- 1561(line=69, offs=23)
*/
ATSINSlab(__atstmplab11):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1565(line=69, offs=27) -- 1570(line=69, offs=32)
*/
ATSINSmove(tmpret11, ATSPMVbool_false()) ;
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret11) ;
} /* end of [build_057_bats_modules_057_list_057_src_057_lib_056_sats__is_nil__6] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 1773(line=78, offs=23) -- 2101(line=88, offs=31)
*/
/*
local: 
global: reverse$7$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8532)
tmparg = S2Evar(a(8532))
tmpsub = None()
*/
atstype_boxed
build_057_bats_modules_057_list_057_src_057_lib_056_sats__reverse__7(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret12, atstype_boxed) ;
ATStmpdec(tmp17, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1765(line=78, offs=15) -- 2101(line=88, offs=31)
*/
ATSINSflab(__patsflab_reverse):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1780(line=78, offs=30) -- 2101(line=88, offs=31)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2079(line=88, offs=9) -- 2092(line=88, offs=22)
*/

ATSINSmove_nil(tmp17) ;

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2074(line=88, offs=4) -- 2097(line=88, offs=27)
*/
ATSINSmove(tmpret12, ATSfunclo_fun(PMVd2vfunlab(d2v=loop$4750(1), flab=loop_8$0(level=1)), (atstype_boxed, atstype_boxed), atstype_boxed)(tmp17, arg0)) ;

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1780(line=78, offs=30) -- 2101(line=88, offs=31)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret12) ;
} /* end of [build_057_bats_modules_057_list_057_src_057_lib_056_sats__reverse__7] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 1790(line=79, offs=7) -- 2070(line=87, offs=30)
*/
/*
local: loop_8$0(level=1)
global: loop_8$0(level=1)
local: 
global: 
*/
ATSstatic()
atstype_boxed
loop_8__8(atstype_boxed arg0, atstype_boxed arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstype_boxed) ;
ATStmpdec(apy1, atstype_boxed) ;
ATStmpdec(tmpret13, atstype_boxed) ;
ATStmpdec(tmp16, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1790(line=79, offs=7) -- 2070(line=87, offs=30)
*/
ATSINSflab(__patsflab_loop_8):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1885(line=81, offs=5) -- 2070(line=87, offs=30)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1905(line=82, offs=7) -- 1919(line=82, offs=21)
*/
ATSINSlab(__atstmplab12):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1841(line=80, offs=26) -- 1845(line=80, offs=30)
*/
ATSifthen(ATSCKptriscons(arg1)) { ATSINSgoto(__atstmplab15) ; } ;
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1919(line=82, offs=21) -- 1919(line=82, offs=21)
*/
ATSINSlab(__atstmplab13):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1923(line=82, offs=25) -- 1926(line=82, offs=28)
*/
ATSINSmove(tmpret13, arg0) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1933(line=83, offs=7) -- 1953(line=83, offs=27)
*/
ATSINSlab(__atstmplab14):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1841(line=80, offs=26) -- 1845(line=80, offs=30)
*/
#if(0)
ATSifthen(ATSCKptrisnull(arg1)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1953(line=83, offs=27) -- 1953(line=83, offs=27)
*/
ATSINSlab(__atstmplab15):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1957(line=83, offs=31) -- 2070(line=87, offs=30)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1980(line=84, offs=20) -- 1982(line=84, offs=22)
*/
ATSINSmove(tmp16, ATSSELcon(arg1, postiats_tysum_3, atslab__1)) ;
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2000(line=85, offs=18) -- 2009(line=85, offs=27)
*/
ATSINSstore(ATSSELcon(arg1, postiats_tysum_3, atslab__1), arg0) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2050(line=87, offs=10) -- 2066(line=87, offs=26)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, arg1) ;
ATSINSmove_tlcal(apy1, tmp16) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSfgoto(__patsflab_loop_8) ;
ATStailcal_end()

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1957(line=83, offs=31) -- 2070(line=87, offs=30)
*/
/*
INSletpop()
*/
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret13) ;
} /* end of [loop_8__8] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 2305(line=101, offs=20) -- 2349(line=102, offs=38)
*/
/*
local: 
global: head$9$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8539)
tmparg = S2Evar(a(8539))
tmpsub = None()
*/
atstyvar_type(a)
build_057_bats_modules_057_list_057_src_057_lib_056_sats__head__9(atsrefarg0_type(atstype_boxed) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret18, atstyvar_type(a)) ;
ATStmpdec(tmp19, atstyvar_type(a)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2300(line=101, offs=15) -- 2349(line=102, offs=38)
*/
ATSINSflab(__patsflab_head):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2314(line=102, offs=3) -- 2349(line=102, offs=38)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2326(line=102, offs=15) -- 2344(line=102, offs=33)
*/
ATSINSlab(__atstmplab16):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2306(line=101, offs=21) -- 2308(line=101, offs=23)
*/
#if(0)
ATSifthen(ATSCKptrisnull(arg0)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2344(line=102, offs=33) -- 2344(line=102, offs=33)
*/
ATSINSlab(__atstmplab17):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2339(line=102, offs=28) -- 2340(line=102, offs=29)
*/
ATSINSmove(tmp19, ATSSELcon(arg0, postiats_tysum_4, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2348(line=102, offs=37) -- 2349(line=102, offs=38)
*/
ATSINSmove(tmpret18, tmp19) ;
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret18) ;
} /* end of [build_057_bats_modules_057_list_057_src_057_lib_056_sats__head__9] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 2370(line=104, offs=20) -- 2417(line=105, offs=41)
*/
/*
local: 
global: tail$10$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8543)
tmparg = S2Evar(a(8543))
tmpsub = None()
*/
atstype_boxed
build_057_bats_modules_057_list_057_src_057_lib_056_sats__tail__10(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret21, atstype_boxed) ;
ATStmpdec(tmp23, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2365(line=104, offs=15) -- 2417(line=105, offs=41)
*/
ATSINSflab(__patsflab_tail):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2379(line=105, offs=3) -- 2417(line=105, offs=41)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2391(line=105, offs=15) -- 2411(line=105, offs=35)
*/
ATSINSlab(__atstmplab18):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2371(line=104, offs=21) -- 2373(line=104, offs=23)
*/
#if(0)
ATSifthen(ATSCKptrisnull(arg0)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2411(line=105, offs=35) -- 2411(line=105, offs=35)
*/
ATSINSlab(__atstmplab19):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2408(line=105, offs=32) -- 2410(line=105, offs=34)
*/
ATSINSmove(tmp23, ATSSELcon(arg0, postiats_tysum_5, atslab__1)) ;
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2391(line=105, offs=15) -- 2417(line=105, offs=41)
*/
ATSINSfreecon(arg0) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2415(line=105, offs=39) -- 2417(line=105, offs=41)
*/
ATSINSmove(tmpret21, tmp23) ;
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret21) ;
} /* end of [build_057_bats_modules_057_list_057_src_057_lib_056_sats__tail__10] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 2789(line=122, offs=26) -- 3056(line=130, offs=19)
*/
/*
local: 
global: map$11$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8547), b(8548)
tmparg = S2Evar(a(8547)); S2Evar(b(8548))
tmpsub = None()
*/
atstype_boxed
build_057_bats_modules_057_list_057_src_057_lib_056_sats__map__11(atsrefarg0_type(atstype_boxed) arg0, atsrefarg1_type(atstyclo_top) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret24, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2781(line=122, offs=18) -- 3056(line=130, offs=19)
*/
ATSINSflab(__patsflab_map):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2799(line=122, offs=36) -- 3056(line=130, offs=19)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3041(line=130, offs=4) -- 3052(line=130, offs=15)
*/
ATSINSmove(tmpret24, ATSfunclo_fun(PMVd2vfunlab(d2v=loop$4761(1), flab=loop_12$0(level=1)), (atsrefarg0_type(atstype_boxed), atsrefarg1_type(atstyclo_top)), atstype_boxed)(ATSPMVrefarg0(arg0), ATSPMVrefarg1(arg1))) ;

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2799(line=122, offs=36) -- 3056(line=130, offs=19)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret24) ;
} /* end of [build_057_bats_modules_057_list_057_src_057_lib_056_sats__map__11] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 2809(line=123, offs=7) -- 3037(line=129, offs=42)
*/
/*
local: loop_12$0(level=1)
global: loop_12$0(level=1)
local: 
global: 
*/
ATSstatic()
atstype_boxed
loop_12__12(atsrefarg0_type(atstype_boxed) arg0, atsrefarg1_type(atstyclo_top) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret25, atstype_boxed) ;
ATStmpdec(tmp26, atstyvar_type(a)) ;
ATStmpdec(tmp27, atstype_boxed) ;
ATStmpdec(tmp28, atstyvar_type(b)) ;
ATStmpdec(tmp29, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2809(line=123, offs=7) -- 3037(line=129, offs=42)
*/
ATSINSflab(__patsflab_loop_12):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2893(line=125, offs=5) -- 3037(line=129, offs=42)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2911(line=126, offs=7) -- 2924(line=126, offs=20)
*/
ATSINSlab(__atstmplab20):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2833(line=124, offs=6) -- 2835(line=124, offs=8)
*/
ATSifthen(ATSCKptriscons(arg0)) { ATSINSgoto(__atstmplab23) ; } ;
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2924(line=126, offs=20) -- 2924(line=126, offs=20)
*/
ATSINSlab(__atstmplab21):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2928(line=126, offs=24) -- 2941(line=126, offs=37)
*/

ATSINSmove_nil(tmpret25) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2948(line=127, offs=7) -- 2967(line=127, offs=26)
*/
ATSINSlab(__atstmplab22):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2833(line=124, offs=6) -- 2835(line=124, offs=8)
*/
#if(0)
ATSifthen(ATSCKptrisnull(arg0)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2967(line=127, offs=26) -- 2967(line=127, offs=26)
*/
ATSINSlab(__atstmplab23):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2961(line=127, offs=20) -- 2962(line=127, offs=21)
*/
ATSINSmove(tmp26, ATSSELcon(arg0, postiats_tysum_6, atslab__0)) ;
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2964(line=127, offs=23) -- 2966(line=127, offs=25)
*/
ATSINSmove(tmp27, ATSSELcon(arg0, postiats_tysum_6, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2971(line=127, offs=30) -- 3037(line=129, offs=42)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2991(line=128, offs=17) -- 2994(line=128, offs=20)
*/
ATSINSmove(tmp28, ATSfunclo_clo(ATSPMVrefarg1(arg1), (atstype_cloptr, atstyvar_type(a)), atstyvar_type(b))(ATSPMVrefarg1(arg1), tmp26)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3021(line=129, offs=26) -- 3032(line=129, offs=37)
*/
ATSINSmove(tmp29, ATSfunclo_fun(PMVd2vfunlab(d2v=loop$4761(1), flab=loop_12$0(level=1)), (atsrefarg0_type(atstype_boxed), atsrefarg1_type(atstyclo_top)), atstype_boxed)(ATSPMVrefarg0(tmp27), ATSPMVrefarg1(arg1))) ;

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3005(line=129, offs=10) -- 3033(line=129, offs=38)
*/

/*
#LINCONSTATUS==0
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret25, postiats_tysum_7) ;
#if(0)
ATSINSstore_con1_tag(tmpret25, 1) ;
#endif
ATSINSstore_con1_ofs(tmpret25, postiats_tysum_7, atslab__0, tmp28) ;
ATSINSstore_con1_ofs(tmpret25, postiats_tysum_7, atslab__1, tmp29) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2971(line=127, offs=30) -- 3037(line=129, offs=42)
*/
/*
INSletpop()
*/
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret25) ;
} /* end of [loop_12__12] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 3085(line=132, offs=28) -- 3309(line=138, offs=25)
*/
/*
local: 
global: foldl$13$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8555), b(8556)
tmparg = S2Evar(a(8555)); S2Evar(b(8556))
tmpsub = None()
*/
atstyvar_type(b)
build_057_bats_modules_057_list_057_src_057_lib_056_sats__foldl__13(atsrefarg0_type(atstype_boxed) arg0, atstyvar_type(b) arg1, atsrefarg1_type(atstyclo_top) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret30, atstyvar_type(b)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3075(line=132, offs=18) -- 3309(line=138, offs=25)
*/
ATSINSflab(__patsflab_foldl):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3101(line=132, offs=44) -- 3309(line=138, offs=25)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3288(line=138, offs=4) -- 3305(line=138, offs=21)
*/
ATSINSmove(tmpret30, ATSfunclo_fun(PMVd2vfunlab(d2v=loop$4770(1), flab=loop_14$0(level=1)), (atsrefarg0_type(atstype_boxed), atstyvar_type(b), atsrefarg1_type(atstyclo_top)), atstyvar_type(b))(ATSPMVrefarg0(arg0), arg1, ATSPMVrefarg1(arg2))) ;

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3101(line=132, offs=44) -- 3309(line=138, offs=25)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret30) ;
} /* end of [build_057_bats_modules_057_list_057_src_057_lib_056_sats__foldl__13] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 3111(line=133, offs=7) -- 3284(line=137, offs=52)
*/
/*
local: loop_14$0(level=1)
global: loop_14$0(level=1)
local: 
global: 
*/
ATSstatic()
atstyvar_type(b)
loop_14__14(atsrefarg0_type(atstype_boxed) arg0, atstyvar_type(b) arg1, atsrefarg1_type(atstyclo_top) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atsrefarg0_type(atstype_boxed)) ;
ATStmpdec(apy1, atstyvar_type(b)) ;
ATStmpdec(apy2, atsrefarg1_type(atstyclo_top)) ;
ATStmpdec(tmpret31, atstyvar_type(b)) ;
ATStmpdec(tmp32, atstyvar_type(a)) ;
ATStmpdec(tmp33, atstype_boxed) ;
ATStmpdec(tmp34, atstyvar_type(b)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3111(line=133, offs=7) -- 3284(line=137, offs=52)
*/
ATSINSflab(__patsflab_loop_14):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3194(line=135, offs=5) -- 3284(line=137, offs=52)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3212(line=136, offs=7) -- 3225(line=136, offs=20)
*/
ATSINSlab(__atstmplab24):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3135(line=134, offs=6) -- 3137(line=134, offs=8)
*/
ATSifthen(ATSCKptriscons(arg0)) { ATSINSgoto(__atstmplab27) ; } ;
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3225(line=136, offs=20) -- 3225(line=136, offs=20)
*/
ATSINSlab(__atstmplab25):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3229(line=136, offs=24) -- 3232(line=136, offs=27)
*/
ATSINSmove(tmpret31, arg1) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3239(line=137, offs=7) -- 3258(line=137, offs=26)
*/
ATSINSlab(__atstmplab26):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3135(line=134, offs=6) -- 3137(line=134, offs=8)
*/
#if(0)
ATSifthen(ATSCKptrisnull(arg0)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3258(line=137, offs=26) -- 3258(line=137, offs=26)
*/
ATSINSlab(__atstmplab27):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3252(line=137, offs=20) -- 3253(line=137, offs=21)
*/
ATSINSmove(tmp32, ATSSELcon(arg0, postiats_tysum_8, atslab__0)) ;
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3255(line=137, offs=23) -- 3257(line=137, offs=25)
*/
ATSINSmove(tmp33, ATSSELcon(arg0, postiats_tysum_8, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3271(line=137, offs=39) -- 3280(line=137, offs=48)
*/
ATSINSmove(tmp34, ATSfunclo_clo(ATSPMVrefarg1(arg2), (atstype_cloptr, atstyvar_type(b), atstyvar_type(a)), atstyvar_type(b))(ATSPMVrefarg1(arg2), arg1, tmp32)) ;

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3262(line=137, offs=30) -- 3284(line=137, offs=52)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, ATSPMVrefarg0(tmp33)) ;
ATSINSmove_tlcal(apy1, tmp34) ;
ATSINSmove_tlcal(apy2, ATSPMVrefarg1(arg2)) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSargmove_tlcal(arg2, apy2) ;
ATSINSfgoto(__patsflab_loop_14) ;
ATStailcal_end()

ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret31) ;
} /* end of [loop_14__14] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 3534(line=147, offs=29) -- 3813(line=156, offs=20)
*/
/*
local: 
global: append$15$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8563)
tmparg = S2Evar(a(8563))
tmpsub = None()
*/
atstype_boxed
build_057_bats_modules_057_list_057_src_057_lib_056_sats__append__15(atstype_boxed arg0, atstype_boxed arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret35, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3520(line=147, offs=15) -- 3813(line=156, offs=20)
*/
ATSINSflab(__patsflab_append):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3545(line=147, offs=40) -- 3813(line=156, offs=20)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3797(line=156, offs=4) -- 3809(line=156, offs=16)
*/
ATSINSmove(tmpret35, ATSfunclo_fun(PMVd2vfunlab(d2v=loop$4778(1), flab=loop_16$0(level=1)), (atstype_boxed, atstype_boxed), atstype_boxed)(arg0, arg1)) ;

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3545(line=147, offs=40) -- 3813(line=156, offs=20)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret35) ;
} /* end of [build_057_bats_modules_057_list_057_src_057_lib_056_sats__append__15] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 3555(line=148, offs=7) -- 3793(line=155, offs=16)
*/
/*
local: loop_16$0(level=1)
global: loop_16$0(level=1)
local: 
global: 
*/
ATSstatic()
atstype_boxed
loop_16__16(atstype_boxed arg0, atstype_boxed arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret36, atstype_boxed) ;
ATStmpdec(tmp39, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3555(line=148, offs=7) -- 3793(line=155, offs=16)
*/
ATSINSflab(__patsflab_loop_16):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3640(line=150, offs=5) -- 3793(line=155, offs=16)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3658(line=151, offs=7) -- 3672(line=151, offs=21)
*/
ATSINSlab(__atstmplab28):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3579(line=149, offs=6) -- 3581(line=149, offs=8)
*/
ATSifthen(ATSCKptriscons(arg0)) { ATSINSgoto(__atstmplab31) ; } ;
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3672(line=151, offs=21) -- 3672(line=151, offs=21)
*/
ATSINSlab(__atstmplab29):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3676(line=151, offs=25) -- 3678(line=151, offs=27)
*/
ATSINSmove(tmpret36, arg1) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3685(line=152, offs=7) -- 3705(line=152, offs=27)
*/
ATSINSlab(__atstmplab30):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3579(line=149, offs=6) -- 3581(line=149, offs=8)
*/
#if(0)
ATSifthen(ATSCKptrisnull(arg0)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3705(line=152, offs=27) -- 3705(line=152, offs=27)
*/
ATSINSlab(__atstmplab31):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3709(line=152, offs=31) -- 3793(line=155, offs=16)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3736(line=153, offs=24) -- 3748(line=153, offs=36)
*/
ATSINSmove(tmp39, ATSfunclo_fun(PMVd2vfunlab(d2v=loop$4778(1), flab=loop_16$0(level=1)), (atstype_boxed, atstype_boxed), atstype_boxed)(ATSSELcon(arg0, postiats_tysum_9, atslab__1), arg1)) ;

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3730(line=153, offs=18) -- 3748(line=153, offs=36)
*/
ATSINSstore(ATSSELcon(arg0, postiats_tysum_9, atslab__1), tmp39) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3787(line=155, offs=10) -- 3789(line=155, offs=12)
*/
ATSINSmove(tmpret36, arg0) ;
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 3709(line=152, offs=31) -- 3793(line=155, offs=16)
*/
/*
INSletpop()
*/
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret36) ;
} /* end of [loop_16__16] */
#endif // end of [TEMPLATE]

/*
** for initialization(dynloading)
*/
ATSextern()
atsvoid_t0ype
build_057_bats_modules_057_list_057_src_057_lib_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_ext(
build_057_bats_modules_057_list_057_src_057_lib_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
build_057_bats_modules_057_list_057_src_057_lib_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(build_057_bats_modules_057_list_057_src_057_lib_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/* ****** ****** */

/* end-of-compilation-unit */
