/*
**
** The C code is generated by [ATS/Postiats-0-4-1]
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
$(PATSHOME)/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
$(PATSHOME)/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
$(PATSHOME)/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
$(PATSHOME)/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
$(PATSHOME)/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
$(PATSHOME)/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_0 ;
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_1 ;
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_2 ;
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_3 ;
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_4 ;
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_5 ;
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstyvar_type(b) atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_6 ;
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_7 ;
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstyvar_type(a) atslab__0 ;
atstype_boxed atslab__1 ;
} postiats_tysum_8 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
#if(0)
#if(0)
ATSextern()
atstype_boxed
build_057_bats_modules_057_list_057_src_057_lib_056_sats__nil__0() ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstype_boxed
build_057_bats_modules_057_list_057_src_057_lib_056_sats__cons__1(atstyvar_type(a), atstype_boxed) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_int)
build_057_bats_modules_057_list_057_src_057_lib_056_sats__length__2(atstype_boxed) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstatic()
atstkind_t0ype(atstype_int)
loop_3__3(atstype_boxed) ;
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstype_boxed
build_057_bats_modules_057_list_057_src_057_lib_056_sats__reverse__4(atstype_boxed) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstatic()
atstype_boxed
loop_5__5(atstype_boxed, atstype_boxed) ;
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstyvar_type(a)
build_057_bats_modules_057_list_057_src_057_lib_056_sats__head__6(atstype_boxed) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstype_boxed
build_057_bats_modules_057_list_057_src_057_lib_056_sats__tail__7(atstype_boxed) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstype_boxed
build_057_bats_modules_057_list_057_src_057_lib_056_sats__map__8(atstype_boxed, atstype_cloptr) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstatic()
atstype_boxed
loop_9__9(atstype_boxed, atstype_cloptr) ;
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstyvar_type(b)
build_057_bats_modules_057_list_057_src_057_lib_056_sats__foldl__10(atstype_boxed, atstyvar_type(b), atstype_cloptr) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstatic()
atstyvar_type(b)
loop_11__11(atstype_boxed, atstyvar_type(b), atstype_cloptr) ;
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstype_boxed
build_057_bats_modules_057_list_057_src_057_lib_056_sats__append__12(atstype_boxed, atstype_boxed) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
ATSstatic()
atstype_boxed
loop_13__13(atstype_boxed, atstype_boxed) ;
#endif // end of [TEMPLATE]

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
build_057_bats_modules_057_list_057_src_057_lib_056_sats__is_nil__14(atstype_boxed) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 420(line=25, offs=19) -- 435(line=25, offs=34)
*/
/*
local: 
global: nil$0$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8512)
tmparg = S2Evar(a(8512))
tmpsub = None()
*/
atstype_boxed
build_057_bats_modules_057_list_057_src_057_lib_056_sats__nil__0()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 416(line=25, offs=15) -- 435(line=25, offs=34)
*/
ATSINSflab(__patsflab_nil):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 425(line=25, offs=24) -- 435(line=25, offs=34)
*/

ATSINSmove_nil(tmpret0) ;

ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [build_057_bats_modules_057_list_057_src_057_lib_056_sats__nil__0] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 456(line=27, offs=20) -- 482(line=27, offs=46)
*/
/*
local: 
global: cons$1$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8513)
tmparg = S2Evar(a(8513))
tmpsub = None()
*/
atstype_boxed
build_057_bats_modules_057_list_057_src_057_lib_056_sats__cons__1(atstyvar_type(a) arg0, atstype_boxed arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret1, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 451(line=27, offs=15) -- 482(line=27, offs=46)
*/
ATSINSflab(__patsflab_cons):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 466(line=27, offs=30) -- 482(line=27, offs=46)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret1, postiats_tysum_0) ;
#if(0)
ATSINSstore_con1_tag(tmpret1, 1) ;
#endif
ATSINSstore_con1_ofs(tmpret1, postiats_tysum_0, atslab__0, arg0) ;
ATSINSstore_con1_ofs(tmpret1, postiats_tysum_0, atslab__1, arg1) ;
ATSINSmove_con1_end()
ATSfunbody_end()
ATSreturn(tmpret1) ;
} /* end of [build_057_bats_modules_057_list_057_src_057_lib_056_sats__cons__1] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 654(line=36, offs=26) -- 815(line=42, offs=16)
*/
/*
local: 
global: length$2$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8515)
tmparg = S2Evar(a(8515))
tmpsub = None()
*/
atstkind_t0ype(atstype_int)
build_057_bats_modules_057_list_057_src_057_lib_056_sats__length__2(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 643(line=36, offs=15) -- 815(line=42, offs=16)
*/
ATSINSflab(__patsflab_length):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 661(line=36, offs=33) -- 815(line=42, offs=16)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 803(line=42, offs=4) -- 810(line=42, offs=11)
*/
ATSINSmove(tmpret2, ATSfunclo_fun(PMVd2vfunlab(d2v=loop$4740(1), flab=loop_3$0(level=1)), (atstype_boxed), atstkind_t0ype(atstype_int))(arg0)) ;

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 661(line=36, offs=33) -- 815(line=42, offs=16)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret2) ;
} /* end of [build_057_bats_modules_057_list_057_src_057_lib_056_sats__length__2] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 671(line=37, offs=7) -- 799(line=41, offs=39)
*/
/*
local: loop_3$0(level=1)
global: loop_3$0(level=1)
local: 
global: 
*/
ATSstatic()
atstkind_t0ype(atstype_int)
loop_3__3(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret3, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp5, atstype_boxed) ;
ATStmpdec(tmp6, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 671(line=37, offs=7) -- 799(line=41, offs=39)
*/
ATSINSflab(__patsflab_loop_3):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 727(line=39, offs=5) -- 799(line=41, offs=39)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 745(line=40, offs=7) -- 755(line=40, offs=17)
*/
ATSINSlab(__atstmplab0):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 695(line=38, offs=6) -- 697(line=38, offs=8)
*/
ATSifthen(ATSCKptriscons(arg0)) { ATSINSgoto(__atstmplab3) ; } ;
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 755(line=40, offs=17) -- 755(line=40, offs=17)
*/
ATSINSlab(__atstmplab1):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 759(line=40, offs=21) -- 760(line=40, offs=22)
*/
ATSINSmove(tmpret3, ATSPMVi0nt(0)) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 767(line=41, offs=7) -- 783(line=41, offs=23)
*/
ATSINSlab(__atstmplab2):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 695(line=38, offs=6) -- 697(line=38, offs=8)
*/
#if(0)
ATSifthen(ATSCKptrisnull(arg0)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 783(line=41, offs=23) -- 783(line=41, offs=23)
*/
ATSINSlab(__atstmplab3):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 780(line=41, offs=20) -- 782(line=41, offs=22)
*/
ATSINSmove(tmp5, ATSSELcon(arg0, postiats_tysum_1, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 791(line=41, offs=31) -- 798(line=41, offs=38)
*/
ATSINSmove(tmp6, ATSfunclo_fun(PMVd2vfunlab(d2v=loop$4740(1), flab=loop_3$0(level=1)), (atstype_boxed), atstkind_t0ype(atstype_int))(tmp5)) ;

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 787(line=41, offs=27) -- 798(line=41, offs=38)
*/
ATSINSmove(tmpret3, PMVtmpltcst(g1int_add<S2Eextkind(atstype_int)>)(ATSPMVi0nt(1), tmp6)) ;

ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret3) ;
} /* end of [loop_3__3] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 985(line=51, offs=23) -- 1213(line=57, offs=28)
*/
/*
local: 
global: reverse$4$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8522)
tmparg = S2Evar(a(8522))
tmpsub = None()
*/
atstype_boxed
build_057_bats_modules_057_list_057_src_057_lib_056_sats__reverse__4(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret7, atstype_boxed) ;
ATStmpdec(tmp12, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 977(line=51, offs=15) -- 1213(line=57, offs=28)
*/
ATSINSflab(__patsflab_reverse):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 992(line=51, offs=30) -- 1213(line=57, offs=28)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1194(line=57, offs=9) -- 1204(line=57, offs=19)
*/

ATSINSmove_nil(tmp12) ;

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1189(line=57, offs=4) -- 1209(line=57, offs=24)
*/
ATSINSmove(tmpret7, ATSfunclo_fun(PMVd2vfunlab(d2v=loop$4744(1), flab=loop_5$0(level=1)), (atstype_boxed, atstype_boxed), atstype_boxed)(tmp12, arg0)) ;

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 992(line=51, offs=30) -- 1213(line=57, offs=28)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret7) ;
} /* end of [build_057_bats_modules_057_list_057_src_057_lib_056_sats__reverse__4] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 1002(line=52, offs=7) -- 1185(line=56, offs=54)
*/
/*
local: loop_5$0(level=1)
global: loop_5$0(level=1)
local: 
global: 
*/
ATSstatic()
atstype_boxed
loop_5__5(atstype_boxed arg0, atstype_boxed arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstype_boxed) ;
ATStmpdec(apy1, atstype_boxed) ;
ATStmpdec(tmpret8, atstype_boxed) ;
ATStmpdec(tmp9, atstyvar_type(a)) ;
ATStmpdec(tmp10, atstype_boxed) ;
ATStmpdec(tmp11, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1002(line=52, offs=7) -- 1185(line=56, offs=54)
*/
ATSINSflab(__patsflab_loop_5):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1094(line=54, offs=5) -- 1185(line=56, offs=54)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1114(line=55, offs=7) -- 1124(line=55, offs=17)
*/
ATSINSlab(__atstmplab4):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1052(line=53, offs=25) -- 1056(line=53, offs=29)
*/
ATSifthen(ATSCKptriscons(arg1)) { ATSINSgoto(__atstmplab7) ; } ;
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1124(line=55, offs=17) -- 1124(line=55, offs=17)
*/
ATSINSlab(__atstmplab5):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1128(line=55, offs=21) -- 1131(line=55, offs=24)
*/
ATSINSmove(tmpret8, arg0) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1138(line=56, offs=7) -- 1154(line=56, offs=23)
*/
ATSINSlab(__atstmplab6):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1052(line=53, offs=25) -- 1056(line=53, offs=29)
*/
#if(0)
ATSifthen(ATSCKptrisnull(arg1)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1154(line=56, offs=23) -- 1154(line=56, offs=23)
*/
ATSINSlab(__atstmplab7):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1148(line=56, offs=17) -- 1149(line=56, offs=18)
*/
ATSINSmove(tmp9, ATSSELcon(arg1, postiats_tysum_2, atslab__0)) ;
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1151(line=56, offs=20) -- 1153(line=56, offs=22)
*/
ATSINSmove(tmp10, ATSSELcon(arg1, postiats_tysum_2, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1163(line=56, offs=32) -- 1180(line=56, offs=49)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmp11, postiats_tysum_2) ;
#if(0)
ATSINSstore_con1_tag(tmp11, 1) ;
#endif
ATSINSstore_con1_ofs(tmp11, postiats_tysum_2, atslab__0, tmp9) ;
ATSINSstore_con1_ofs(tmp11, postiats_tysum_2, atslab__1, arg0) ;
ATSINSmove_con1_end()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1158(line=56, offs=27) -- 1185(line=56, offs=54)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, tmp11) ;
ATSINSmove_tlcal(apy1, tmp10) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSfgoto(__patsflab_loop_5) ;
ATStailcal_end()

ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret8) ;
} /* end of [loop_5__5] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 1389(line=69, offs=20) -- 1430(line=70, offs=35)
*/
/*
local: 
global: head$6$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8529)
tmparg = S2Evar(a(8529))
tmpsub = None()
*/
atstyvar_type(a)
build_057_bats_modules_057_list_057_src_057_lib_056_sats__head__6(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret13, atstyvar_type(a)) ;
ATStmpdec(tmp14, atstyvar_type(a)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1384(line=69, offs=15) -- 1430(line=70, offs=35)
*/
ATSINSflab(__patsflab_head):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1398(line=70, offs=3) -- 1430(line=70, offs=35)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1410(line=70, offs=15) -- 1425(line=70, offs=30)
*/
ATSINSlab(__atstmplab8):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1390(line=69, offs=21) -- 1392(line=69, offs=23)
*/
#if(0)
ATSifthen(ATSCKptrisnull(arg0)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1425(line=70, offs=30) -- 1425(line=70, offs=30)
*/
ATSINSlab(__atstmplab9):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1420(line=70, offs=25) -- 1421(line=70, offs=26)
*/
ATSINSmove(tmp14, ATSSELcon(arg0, postiats_tysum_3, atslab__0)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1429(line=70, offs=34) -- 1430(line=70, offs=35)
*/
ATSINSmove(tmpret13, tmp14) ;
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret13) ;
} /* end of [build_057_bats_modules_057_list_057_src_057_lib_056_sats__head__6] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 1451(line=72, offs=20) -- 1494(line=73, offs=37)
*/
/*
local: 
global: tail$7$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8533)
tmparg = S2Evar(a(8533))
tmpsub = None()
*/
atstype_boxed
build_057_bats_modules_057_list_057_src_057_lib_056_sats__tail__7(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret16, atstype_boxed) ;
ATStmpdec(tmp18, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1446(line=72, offs=15) -- 1494(line=73, offs=37)
*/
ATSINSflab(__patsflab_tail):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1460(line=73, offs=3) -- 1494(line=73, offs=37)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1472(line=73, offs=15) -- 1488(line=73, offs=31)
*/
ATSINSlab(__atstmplab10):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1452(line=72, offs=21) -- 1454(line=72, offs=23)
*/
#if(0)
ATSifthen(ATSCKptrisnull(arg0)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1488(line=73, offs=31) -- 1488(line=73, offs=31)
*/
ATSINSlab(__atstmplab11):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1485(line=73, offs=28) -- 1487(line=73, offs=30)
*/
ATSINSmove(tmp18, ATSSELcon(arg0, postiats_tysum_4, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1492(line=73, offs=35) -- 1494(line=73, offs=37)
*/
ATSINSmove(tmpret16, tmp18) ;
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret16) ;
} /* end of [build_057_bats_modules_057_list_057_src_057_lib_056_sats__tail__7] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 1672(line=82, offs=26) -- 1891(line=88, offs=19)
*/
/*
local: 
global: map$8$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8537), b(8538)
tmparg = S2Evar(a(8537)); S2Evar(b(8538))
tmpsub = None()
*/
atstype_boxed
build_057_bats_modules_057_list_057_src_057_lib_056_sats__map__8(atstype_boxed arg0, atstype_cloptr arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret19, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1664(line=82, offs=18) -- 1891(line=88, offs=19)
*/
ATSINSflab(__patsflab_map):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1682(line=82, offs=36) -- 1891(line=88, offs=19)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1876(line=88, offs=4) -- 1887(line=88, offs=15)
*/
ATSINSmove(tmpret19, ATSfunclo_fun(PMVd2vfunlab(d2v=loop$4755(1), flab=loop_9$0(level=1)), (atstype_boxed, atstype_cloptr), atstype_boxed)(arg0, arg1)) ;

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1682(line=82, offs=36) -- 1891(line=88, offs=19)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret19) ;
} /* end of [build_057_bats_modules_057_list_057_src_057_lib_056_sats__map__8] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 1692(line=83, offs=7) -- 1872(line=87, offs=55)
*/
/*
local: loop_9$0(level=1)
global: loop_9$0(level=1)
local: 
global: 
*/
ATSstatic()
atstype_boxed
loop_9__9(atstype_boxed arg0, atstype_cloptr arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret20, atstype_boxed) ;
ATStmpdec(tmp21, atstyvar_type(a)) ;
ATStmpdec(tmp22, atstype_boxed) ;
ATStmpdec(tmp23, atstyvar_type(b)) ;
ATStmpdec(tmp24, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1692(line=83, offs=7) -- 1872(line=87, offs=55)
*/
ATSINSflab(__patsflab_loop_9):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1775(line=85, offs=5) -- 1872(line=87, offs=55)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1793(line=86, offs=7) -- 1803(line=86, offs=17)
*/
ATSINSlab(__atstmplab12):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1716(line=84, offs=6) -- 1718(line=84, offs=8)
*/
ATSifthen(ATSCKptriscons(arg0)) { ATSINSgoto(__atstmplab15) ; } ;
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1803(line=86, offs=17) -- 1803(line=86, offs=17)
*/
ATSINSlab(__atstmplab13):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1807(line=86, offs=21) -- 1817(line=86, offs=31)
*/

ATSINSmove_nil(tmpret20) ;

ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1824(line=87, offs=7) -- 1840(line=87, offs=23)
*/
ATSINSlab(__atstmplab14):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1716(line=84, offs=6) -- 1718(line=84, offs=8)
*/
#if(0)
ATSifthen(ATSCKptrisnull(arg0)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1840(line=87, offs=23) -- 1840(line=87, offs=23)
*/
ATSINSlab(__atstmplab15):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1834(line=87, offs=17) -- 1835(line=87, offs=18)
*/
ATSINSmove(tmp21, ATSSELcon(arg0, postiats_tysum_5, atslab__0)) ;
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1837(line=87, offs=20) -- 1839(line=87, offs=22)
*/
ATSINSmove(tmp22, ATSSELcon(arg0, postiats_tysum_5, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1854(line=87, offs=37) -- 1857(line=87, offs=40)
*/
ATSINSmove(tmp23, ATSfunclo_clo(arg1, (atstype_cloptr, atstyvar_type(a)), atstyvar_type(b))(arg1, tmp21)) ;

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1860(line=87, offs=43) -- 1871(line=87, offs=54)
*/
ATSINSmove(tmp24, ATSfunclo_fun(PMVd2vfunlab(d2v=loop$4755(1), flab=loop_9$0(level=1)), (atstype_boxed, atstype_cloptr), atstype_boxed)(tmp22, arg1)) ;

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1844(line=87, offs=27) -- 1872(line=87, offs=55)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret20, postiats_tysum_6) ;
#if(0)
ATSINSstore_con1_tag(tmpret20, 1) ;
#endif
ATSINSstore_con1_ofs(tmpret20, postiats_tysum_6, atslab__0, tmp23) ;
ATSINSstore_con1_ofs(tmpret20, postiats_tysum_6, atslab__1, tmp24) ;
ATSINSmove_con1_end()
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret20) ;
} /* end of [loop_9__9] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 1923(line=93, offs=28) -- 2141(line=99, offs=25)
*/
/*
local: 
global: foldl$10$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8545), b(8546)
tmparg = S2Evar(a(8545)); S2Evar(b(8546))
tmpsub = None()
*/
atstyvar_type(b)
build_057_bats_modules_057_list_057_src_057_lib_056_sats__foldl__10(atstype_boxed arg0, atstyvar_type(b) arg1, atstype_cloptr arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret25, atstyvar_type(b)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1913(line=93, offs=18) -- 2141(line=99, offs=25)
*/
ATSINSflab(__patsflab_foldl):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1939(line=93, offs=44) -- 2141(line=99, offs=25)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2120(line=99, offs=4) -- 2137(line=99, offs=21)
*/
ATSINSmove(tmpret25, ATSfunclo_fun(PMVd2vfunlab(d2v=loop$4763(1), flab=loop_11$0(level=1)), (atstype_boxed, atstyvar_type(b), atstype_cloptr), atstyvar_type(b))(arg0, arg1, arg2)) ;

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1939(line=93, offs=44) -- 2141(line=99, offs=25)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret25) ;
} /* end of [build_057_bats_modules_057_list_057_src_057_lib_056_sats__foldl__10] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 1949(line=94, offs=7) -- 2116(line=98, offs=49)
*/
/*
local: loop_11$0(level=1)
global: loop_11$0(level=1)
local: 
global: 
*/
ATSstatic()
atstyvar_type(b)
loop_11__11(atstype_boxed arg0, atstyvar_type(b) arg1, atstype_cloptr arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstype_boxed) ;
ATStmpdec(apy1, atstyvar_type(b)) ;
ATStmpdec(apy2, atstype_cloptr) ;
ATStmpdec(tmpret26, atstyvar_type(b)) ;
ATStmpdec(tmp27, atstyvar_type(a)) ;
ATStmpdec(tmp28, atstype_boxed) ;
ATStmpdec(tmp29, atstyvar_type(b)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1949(line=94, offs=7) -- 2116(line=98, offs=49)
*/
ATSINSflab(__patsflab_loop_11):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2032(line=96, offs=5) -- 2116(line=98, offs=49)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2050(line=97, offs=7) -- 2060(line=97, offs=17)
*/
ATSINSlab(__atstmplab16):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1973(line=95, offs=6) -- 1975(line=95, offs=8)
*/
ATSifthen(ATSCKptriscons(arg0)) { ATSINSgoto(__atstmplab19) ; } ;
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2060(line=97, offs=17) -- 2060(line=97, offs=17)
*/
ATSINSlab(__atstmplab17):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2064(line=97, offs=21) -- 2067(line=97, offs=24)
*/
ATSINSmove(tmpret26, arg1) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2074(line=98, offs=7) -- 2090(line=98, offs=23)
*/
ATSINSlab(__atstmplab18):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 1973(line=95, offs=6) -- 1975(line=95, offs=8)
*/
#if(0)
ATSifthen(ATSCKptrisnull(arg0)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2090(line=98, offs=23) -- 2090(line=98, offs=23)
*/
ATSINSlab(__atstmplab19):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2084(line=98, offs=17) -- 2085(line=98, offs=18)
*/
ATSINSmove(tmp27, ATSSELcon(arg0, postiats_tysum_7, atslab__0)) ;
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2087(line=98, offs=20) -- 2089(line=98, offs=22)
*/
ATSINSmove(tmp28, ATSSELcon(arg0, postiats_tysum_7, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2103(line=98, offs=36) -- 2112(line=98, offs=45)
*/
ATSINSmove(tmp29, ATSfunclo_clo(arg2, (atstype_cloptr, atstyvar_type(b), atstyvar_type(a)), atstyvar_type(b))(arg2, arg1, tmp27)) ;

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2094(line=98, offs=27) -- 2116(line=98, offs=49)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, tmp28) ;
ATSINSmove_tlcal(apy1, tmp29) ;
ATSINSmove_tlcal(apy2, arg2) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSargmove_tlcal(arg2, apy2) ;
ATSINSfgoto(__patsflab_loop_11) ;
ATStailcal_end()

ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret26) ;
} /* end of [loop_11__11] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 2316(line=108, offs=29) -- 2526(line=114, offs=20)
*/
/*
local: 
global: append$12$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8553)
tmparg = S2Evar(a(8553))
tmpsub = None()
*/
atstype_boxed
build_057_bats_modules_057_list_057_src_057_lib_056_sats__append__12(atstype_boxed arg0, atstype_boxed arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret30, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2302(line=108, offs=15) -- 2526(line=114, offs=20)
*/
ATSINSflab(__patsflab_append):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2327(line=108, offs=40) -- 2526(line=114, offs=20)
*/
/*
letpush(beg)
*/
/*
letpush(end)
*/

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2510(line=114, offs=4) -- 2522(line=114, offs=16)
*/
ATSINSmove(tmpret30, ATSfunclo_fun(PMVd2vfunlab(d2v=loop$4771(1), flab=loop_13$0(level=1)), (atstype_boxed, atstype_boxed), atstype_boxed)(arg0, arg1)) ;

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2327(line=108, offs=40) -- 2526(line=114, offs=20)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret30) ;
} /* end of [build_057_bats_modules_057_list_057_src_057_lib_056_sats__append__12] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 2337(line=109, offs=7) -- 2506(line=113, offs=53)
*/
/*
local: loop_13$0(level=1)
global: loop_13$0(level=1)
local: 
global: 
*/
ATSstatic()
atstype_boxed
loop_13__13(atstype_boxed arg0, atstype_boxed arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret31, atstype_boxed) ;
ATStmpdec(tmp32, atstyvar_type(a)) ;
ATStmpdec(tmp33, atstype_boxed) ;
ATStmpdec(tmp34, atstype_boxed) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2337(line=109, offs=7) -- 2506(line=113, offs=53)
*/
ATSINSflab(__patsflab_loop_13):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2419(line=111, offs=5) -- 2506(line=113, offs=53)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2437(line=112, offs=7) -- 2447(line=112, offs=17)
*/
ATSINSlab(__atstmplab20):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2361(line=110, offs=6) -- 2363(line=110, offs=8)
*/
ATSifthen(ATSCKptriscons(arg0)) { ATSINSgoto(__atstmplab23) ; } ;
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2447(line=112, offs=17) -- 2447(line=112, offs=17)
*/
ATSINSlab(__atstmplab21):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2451(line=112, offs=21) -- 2453(line=112, offs=23)
*/
ATSINSmove(tmpret31, arg1) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2460(line=113, offs=7) -- 2476(line=113, offs=23)
*/
ATSINSlab(__atstmplab22):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2361(line=110, offs=6) -- 2363(line=110, offs=8)
*/
#if(0)
ATSifthen(ATSCKptrisnull(arg0)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2476(line=113, offs=23) -- 2476(line=113, offs=23)
*/
ATSINSlab(__atstmplab23):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2470(line=113, offs=17) -- 2471(line=113, offs=18)
*/
ATSINSmove(tmp32, ATSSELcon(arg0, postiats_tysum_8, atslab__0)) ;
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2473(line=113, offs=20) -- 2475(line=113, offs=22)
*/
ATSINSmove(tmp33, ATSSELcon(arg0, postiats_tysum_8, atslab__1)) ;
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2493(line=113, offs=40) -- 2505(line=113, offs=52)
*/
ATSINSmove(tmp34, ATSfunclo_fun(PMVd2vfunlab(d2v=loop$4771(1), flab=loop_13$0(level=1)), (atstype_boxed, atstype_boxed), atstype_boxed)(tmp33, arg1)) ;

/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2480(line=113, offs=27) -- 2506(line=113, offs=53)
*/

/*
#LINCONSTATUS==1
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret31, postiats_tysum_8) ;
#if(0)
ATSINSstore_con1_tag(tmpret31, 1) ;
#endif
ATSINSstore_con1_ofs(tmpret31, postiats_tysum_8, atslab__0, tmp32) ;
ATSINSstore_con1_ofs(tmpret31, postiats_tysum_8, atslab__1, tmp34) ;
ATSINSmove_con1_end()
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret31) ;
} /* end of [loop_13__13] */
#endif // end of [TEMPLATE]

#if(0)
/*
build/bats_modules/list/src/lib.dats: 2694(line=123, offs=22) -- 2766(line=126, offs=29)
*/
/*
local: 
global: is_nil$14$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8563)
tmparg = S2Evar(a(8563))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
build_057_bats_modules_057_list_057_src_057_lib_056_sats__is_nil__14(atstype_boxed arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret35, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2687(line=123, offs=15) -- 2766(line=126, offs=29)
*/
ATSINSflab(__patsflab_is_nil):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2703(line=124, offs=3) -- 2766(line=126, offs=29)
*/
ATScaseof_beg()
/*
** ibranchlst-beg
*/
ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2719(line=125, offs=5) -- 2729(line=125, offs=15)
*/
ATSINSlab(__atstmplab24):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2695(line=123, offs=23) -- 2697(line=123, offs=25)
*/
ATSifthen(ATSCKptriscons(arg0)) { ATSINSgoto(__atstmplab27) ; } ;
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2729(line=125, offs=15) -- 2729(line=125, offs=15)
*/
ATSINSlab(__atstmplab25):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2733(line=125, offs=19) -- 2737(line=125, offs=23)
*/
ATSINSmove(tmpret35, ATSPMVbool_true()) ;
ATSbranch_end()

ATSbranch_beg()
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2742(line=126, offs=5) -- 2757(line=126, offs=20)
*/
ATSINSlab(__atstmplab26):
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2695(line=123, offs=23) -- 2697(line=123, offs=25)
*/
#if(0)
ATSifthen(ATSCKptrisnull(arg0)) { ATSINSdeadcode_fail() ; } ;
#endif
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2757(line=126, offs=20) -- 2757(line=126, offs=20)
*/
ATSINSlab(__atstmplab27):
/*
emit_instr: loc0 = : 0(line=0, offs=0) -- 0(line=0, offs=0)
*/
/*
ibranch-mbody:
*/
/*
emit_instr: loc0 = build/bats_modules/list/src/lib.dats: 2761(line=126, offs=24) -- 2766(line=126, offs=29)
*/
ATSINSmove(tmpret35, ATSPMVbool_false()) ;
ATSbranch_end()

/*
** ibranchlst-end
*/
ATScaseof_end()

ATSfunbody_end()
ATSreturn(tmpret35) ;
} /* end of [build_057_bats_modules_057_list_057_src_057_lib_056_sats__is_nil__14] */
#endif // end of [TEMPLATE]

/*
** for initialization(dynloading)
*/
ATSextern()
atsvoid_t0ype
build_057_bats_modules_057_list_057_src_057_lib_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_ext(
build_057_bats_modules_057_list_057_src_057_lib_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
build_057_bats_modules_057_list_057_src_057_lib_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(build_057_bats_modules_057_list_057_src_057_lib_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/* ****** ****** */

/* end-of-compilation-unit */
