/*
**
** The C code is generated by [ATS/Postiats-0-4-1]
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
build/bats_modules/array/src/lib.dats: 2974(line=306, offs=1) -- 4118(line=351, offs=3)
*/

#ifndef _ARR_RUNTIME_DEFINED
#define _ARR_RUNTIME_DEFINED
static inline void
_arr_set_byte(void *p, int off, int v) {
  ((unsigned char *)p)[off] = (unsigned char)v;
}
static inline void
_arr_set_i32(void *p, int off, int v) {
  *(int *)(((char *)p) + off) = v;
}
static inline void
_arr_copy_at(void *dst, int off, void *src, int len) {
  unsigned char *d = ((unsigned char *)dst) + off;
  unsigned char *s = (unsigned char *)src;
  int i;
  for (i = 0; i < len; i++) d[i] = s[i];
}

typedef struct { char *base; int used; int max_sz; } _arr_arena_t;

static inline void *
_arr_arena_create(int max_sz) {
  _arr_arena_t *a;
  a = (void *)malloc(sizeof(_arr_arena_t));
  a->base = (char *)malloc(max_sz);
  a->used = 0;
  a->max_sz = max_sz;
  memset(a->base, 0, max_sz);
  return (void *)a;
}
static inline void *
_arr_arena_alloc(void *arena, int sz) {
  _arr_arena_t *a = (_arr_arena_t *)arena;
  void *p = (void *)(a->base + a->used);
  a->used += sz;
  return p;
}
static inline void
_arr_arena_destroy(void *arena) {
  _arr_arena_t *a = (_arr_arena_t *)arena;
  free(a->base);
  free((void *)a);
}
#endif /* _ARR_RUNTIME_DEFINED */
/*
$(PATSHOME)/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
$(PATSHOME)/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
$(PATSHOME)/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
$(PATSHOME)/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
$(PATSHOME)/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
$(PATSHOME)/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstkind_t0ype(atstype_int) atslab__0 ;
} postiats_tysum_0 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_g1uint2int_size_int)
ATSdyncst_mac(malloc)
ATSdyncst_mac(atspre_g1int_mul_int)
ATSdyncst_mac(atspre_g1int_add_int)
ATSdyncst_extfun(build_057_bats_modules_057_array_057_src_057_lib_056_sats__write_borrow, (atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int), atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int)), atsvoid_t0ype) ;
ATSdyncst_extfun(build_057_bats_modules_057_array_057_src_057_lib_056_sats__write_byte, (atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)), atsvoid_t0ype) ;
ATSdyncst_mac(atspre_g1int2int_int_int)
ATSdyncst_mac(atspre_g1int_gte_int)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
/*
build/bats_modules/env/src/lib.dats: 474(line=17, offs=1) -- 3209(line=109, offs=3)
*/
ATSextcode_beg()
#ifndef _ENV_RUNTIME_DEFINED
#define _ENV_RUNTIME_DEFINED
#include <stdlib.h>
#include <string.h>
#if defined(__APPLE__)
#include <crt_externs.h>
#elif defined(__FreeBSD__) || defined(__DragonFly__) || defined(__NetBSD__) || defined(__OpenBSD__)
#include <sys/types.h>
#include <sys/sysctl.h>
#include <unistd.h>
#else
#include <fcntl.h>
#include <unistd.h>
#endif

static int _env_getenv(const char *name, void *buf, int max_len) {
  const char *val = getenv(name);
  if (!val) return -1;
  int len = (int)strlen(val);
  if (len > max_len) len = max_len;
  memcpy(buf, val, (unsigned int)len);
  return len;
}

/* Copies argv[0..argc) into buf as NUL-terminated strings back to back,
   stopping at max_len bytes. Returns the byte count. */
static int _env_copy_argv(int argc, char **argv, char *buf, int max_len) {
  int i, k = 0;
  for (i = 0; i < argc && k < max_len; i++) {
    int len = (int)strlen(argv[i]) + 1;
    if (len > max_len - k) len = max_len - k;
    memcpy(buf + k, argv[i], (unsigned int)len);
    k += len;
  }
  return k;
}

/* The process's arguments in the format of Linux's /proc/self/cmdline
   (NUL-terminated strings back to back), truncated to max_len bytes;
   -1 when they cannot be read. */
static int _env_args(void *vbuf, int max_len) {
  char *buf = (char *)vbuf;
#if defined(__APPLE__)
  return _env_copy_argv(*_NSGetArgc(), *_NSGetArgv(), buf, max_len);
#elif defined(__OpenBSD__)
  int mib[4] = { CTL_KERN, KERN_PROC_ARGS, 0, KERN_PROC_ARGV };
  size_t sz = 0;
  char **argv;
  int argc = 0, k;
  mib[2] = (int)getpid();
  if (sysctl(mib, 4, NULL, &sz, NULL, 0) != 0) return -1;
  argv = (char **)malloc(sz);
  if (!argv) return -1;
  if (sysctl(mib, 4, argv, &sz, NULL, 0) != 0) { free(argv); return -1; }
  while (argv[argc]) argc++;
  k = _env_copy_argv(argc, argv, buf, max_len);
  free(argv);
  return k;
#elif defined(__FreeBSD__) || defined(__DragonFly__) || defined(__NetBSD__)
#if defined(__NetBSD__)
  int mib[4] = { CTL_KERN, KERN_PROC_ARGS, 0, KERN_PROC_ARGV };
  int pid_at = 2;
#else
  int mib[4] = { CTL_KERN, KERN_PROC, KERN_PROC_ARGS, 0 };
  int pid_at = 3;
#endif
  size_t sz = 0;
  char *all;
  mib[pid_at] = (int)getpid();
  if (sysctl(mib, 4, NULL, &sz, NULL, 0) != 0) return -1;
  all = (char *)malloc(sz);
  if (!all) return -1;
  if (sysctl(mib, 4, all, &sz, NULL, 0) != 0) { free(all); return -1; }
  if (sz > (size_t)max_len) sz = (size_t)max_len;
  memcpy(buf, all, sz);
  free(all);
  return (int)sz;
#else
  int fd = open("/proc/self/cmdline", O_RDONLY);
  int k = 0;
  if (fd < 0) return -1;
  while (k < max_len) {
    int n = (int)read(fd, buf + k, (unsigned int)(max_len - k));
    if (n <= 0) break;
    k += n;
  }
  close(fd);
  return k;
#endif
}
#endif
ATSextcode_end()
#if(0)
ATSextern()
atstype_boxed
build_057_bats_modules_057_env_057_src_057_lib_056_sats__get(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int), atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
build_057_bats_modules_057_array_057_src_057_lib_056_sats__alloc__1(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_type(atstype_ptrk)
build_057_bats_modules_057_array_057_src_057_lib_056_sats__alloc__1__1(atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atsvoid_t0ype
build_057_bats_modules_057_array_057_src_057_lib_056_sats__free__5(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atsvoid_t0ype
build_057_bats_modules_057_array_057_src_057_lib_056_sats__free__5__1(atstkind_type(atstype_ptrk)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__7(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__7__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atstype_boxed
build_057_bats_modules_057_env_057_src_057_lib_056_sats__get_cstr(atsrefarg0_type(atstkind_type(atstype_ptrk)), atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__7__2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atstype_boxed
build_057_bats_modules_057_env_057_src_057_lib_056_sats__args_read(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__7__3(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

/*
build/bats_modules/env/src/lib.dats: 3874(line=143, offs=30) -- 4283(line=155, offs=4)
*/
/*
local: 
global: get$0$0(level=0)
local: 
global: 
*/
ATSextern()
atstype_boxed
build_057_bats_modules_057_env_057_src_057_lib_056_sats__get(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_t0ype(atstype_int) arg1, atsrefarg0_type(atstkind_type(atstype_ptrk)) arg2, atstkind_t0ype(atstype_int) arg3)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstype_boxed) ;
ATStmpdec(tmp1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp12, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp13) ;
// ATStmpdec_void(tmp14) ;
ATStmpdec(tmp15, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp16) ;
ATStmpdec(tmp19, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 3855(line=143, offs=11) -- 4283(line=155, offs=4)
*/
ATSINSflab(__patsflab_get):
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 3907(line=143, offs=63) -- 4283(line=155, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 3940(line=144, offs=30) -- 3952(line=144, offs=42)
*/
ATSINSmove(tmp12, atspre_g1int_add_int(arg1, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 3925(line=144, offs=15) -- 3953(line=144, offs=43)
*/
ATSINSmove(tmp1, build_057_bats_modules_057_array_057_src_057_lib_056_sats__alloc__1__1(tmp12)) ;

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 3965(line=145, offs=12) -- 4006(line=145, offs=53)
*/
ATSINSmove_void(tmp13, build_057_bats_modules_057_array_057_src_057_lib_056_sats__write_borrow(ATSPMVrefarg0(tmp1), ATSPMVi0nt(0), ATSPMVrefarg0(arg0), arg1)) ;

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4018(line=146, offs=12) -- 4051(line=146, offs=45)
*/
ATSINSmove_void(tmp14, build_057_bats_modules_057_array_057_src_057_lib_056_sats__write_byte(ATSPMVrefarg0(tmp1), arg1, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4065(line=147, offs=14) -- 4194(line=150, offs=13)
*/
ATSINSmove(tmp15, ATSextfcall(_env_getenv, (ATSPMVcastfn(castvwtp1, atstkind_type(atstype_ptrk), ATSPMVrefarg0(tmp1)), ATSPMVcastfn(castvwtp1, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg2)), arg3))) ;
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4207(line=151, offs=12) -- 4226(line=151, offs=31)
*/
ATSINSmove_void(tmp16, build_057_bats_modules_057_array_057_src_057_lib_056_sats__free__5__1(tmp1)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4236(line=153, offs=6) -- 4244(line=153, offs=14)
*/
ATSINSmove(tmp19, ATSLIB_056_prelude__gte_g1int_int__7__1(tmp15, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4233(line=153, offs=3) -- 4279(line=154, offs=17)
*/
ATSif(
tmp19
) ATSthen() {
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4250(line=153, offs=20) -- 4261(line=153, offs=31)
*/

/*
#LINCONSTATUS==0
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret0, postiats_tysum_0) ;
#if(0)
ATSINSstore_con1_tag(tmpret0, 0) ;
#endif
ATSINSstore_con1_ofs(tmpret0, postiats_tysum_0, atslab__0, tmp15) ;
ATSINSmove_con1_end()
} ATSelse() {
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4270(line=154, offs=8) -- 4279(line=154, offs=17)
*/

ATSINSmove_nil(tmpret0) ;

} /* ATSendif */
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 3907(line=143, offs=63) -- 4283(line=155, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [build_057_bats_modules_057_env_057_src_057_lib_056_sats__get] */

#if(0)
/*
build/bats_modules/array/src/lib.dats: 4755(line=380, offs=9) -- 4895(line=386, offs=4)
*/
/*
local: 
global: alloc$1$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8684)
tmparg = S2Evar(a(8684))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
build_057_bats_modules_057_array_057_src_057_lib_056_sats__alloc__1(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp3, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp4, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp5, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp6) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4747(line=380, offs=1) -- 4895(line=386, offs=4)
*/
ATSINSflab(__patsflab_alloc):
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4761(line=380, offs=15) -- 4895(line=386, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4784(line=381, offs=20) -- 4799(line=381, offs=35)
*/
ATSINSmove(tmp4, atspre_g1uint2int_size_int(ATSPMVsizeof(atstyvar_type(a)))) ;

/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4780(line=381, offs=16) -- 4799(line=381, offs=35)
*/
ATSINSmove(tmp3, PMVtmpltcst(g1int_mul<S2Eextkind(atstype_int)>)(arg0, tmp4)) ;

/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4810(line=382, offs=11) -- 4830(line=382, offs=31)
*/
ATSINSmove(tmp5, malloc(tmp3)) ;

/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4844(line=383, offs=13) -- 4883(line=383, offs=52)
*/
ATSINSmove_void(tmp6, ATSextfcall(memset, (tmp5, ATSPMVi0nt(0), tmp3))) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4890(line=385, offs=3) -- 4891(line=385, offs=4)
*/
ATSINSmove(tmpret2, tmp5) ;
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4761(line=380, offs=15) -- 4895(line=386, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret2) ;
} /* end of [build_057_bats_modules_057_array_057_src_057_lib_056_sats__alloc__1] */
#endif // end of [TEMPLATE]

/*
build/bats_modules/array/src/lib.dats: 4755(line=380, offs=9) -- 4895(line=386, offs=4)
*/
/*
local: 
global: alloc$1$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = a(8684)
tmparg = S2Evar(a(8684))
tmpsub = Some(a(8684) -> S2Ecst(byte_t0ype))
*/
atstkind_type(atstype_ptrk)
build_057_bats_modules_057_array_057_src_057_lib_056_sats__alloc__1__1(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp3__1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp4__1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp5__1, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp6__1) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4747(line=380, offs=1) -- 4895(line=386, offs=4)
*/
ATSINSflab(__patsflab_alloc):
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4761(line=380, offs=15) -- 4895(line=386, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4784(line=381, offs=20) -- 4799(line=381, offs=35)
*/
ATSINSmove(tmp4__1, atspre_g1uint2int_size_int(ATSPMVsizeof(atstkind_t0ype(atstype_byte)))) ;

/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4780(line=381, offs=16) -- 4799(line=381, offs=35)
*/
ATSINSmove(tmp3__1, atspre_g1int_mul_int(arg0, tmp4__1)) ;

/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4810(line=382, offs=11) -- 4830(line=382, offs=31)
*/
ATSINSmove(tmp5__1, malloc(tmp3__1)) ;

/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4844(line=383, offs=13) -- 4883(line=383, offs=52)
*/
ATSINSmove_void(tmp6__1, ATSextfcall(memset, (tmp5__1, ATSPMVi0nt(0), tmp3__1))) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4890(line=385, offs=3) -- 4891(line=385, offs=4)
*/
ATSINSmove(tmpret2__1, tmp5__1) ;
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4761(line=380, offs=15) -- 4895(line=386, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret2__1) ;
} /* end of [build_057_bats_modules_057_array_057_src_057_lib_056_sats__alloc__1__1] */

#if(0)
/*
build/bats_modules/array/src/lib.dats: 4920(line=389, offs=11) -- 4959(line=390, offs=32)
*/
/*
local: 
global: free$5$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8689)
tmparg = S2Evar(a(8689))
tmpsub = None()
*/
atsvoid_t0ype
build_057_bats_modules_057_array_057_src_057_lib_056_sats__free__5(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret17) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4910(line=389, offs=1) -- 4959(line=390, offs=32)
*/
ATSINSflab(__patsflab_free):
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4931(line=390, offs=4) -- 4959(line=390, offs=32)
*/
ATSINSmove_void(tmpret17, ATSextfcall(free, (arg0))) ;
ATSfunbody_end()
ATSreturn_void(tmpret17) ;
} /* end of [build_057_bats_modules_057_array_057_src_057_lib_056_sats__free__5] */
#endif // end of [TEMPLATE]

/*
build/bats_modules/array/src/lib.dats: 4920(line=389, offs=11) -- 4959(line=390, offs=32)
*/
/*
local: 
global: free$5$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = a(8689)
tmparg = S2Evar(a(8689))
tmpsub = Some(a(8689) -> S2Ecst(byte_t0ype))
*/
atsvoid_t0ype
build_057_bats_modules_057_array_057_src_057_lib_056_sats__free__5__1(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret17__1) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4910(line=389, offs=1) -- 4959(line=390, offs=32)
*/
ATSINSflab(__patsflab_free):
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4931(line=390, offs=4) -- 4959(line=390, offs=32)
*/
ATSINSmove_void(tmpret17__1, ATSextfcall(free, (arg0))) ;
ATSfunbody_end()
ATSreturn_void(tmpret17__1) ;
} /* end of [build_057_bats_modules_057_array_057_src_057_lib_056_sats__free__5__1] */

#if(0)
/*
$(PATSHOME)/prelude/DATS/integer.dats: 12757(line=663, offs=3) -- 12797(line=663, offs=43)
*/
/*
local: 
global: gte_g1int_int$7$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4829)
tmparg = S2Evar(tk(4829))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__7(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret20, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp21, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12741(line=662, offs=1) -- 12797(line=663, offs=43)
*/
ATSINSflab(__patsflab_gte_g1int_int):
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12784(line=663, offs=30) -- 12795(line=663, offs=41)
*/
ATSINSmove(tmp21, PMVtmpltcst(g1int2int<S2Eextkind(atstype_int), S2Evar(tk(4829))>)(arg1)) ;

/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12766(line=663, offs=12) -- 12797(line=663, offs=43)
*/
ATSINSmove(tmpret20, PMVtmpltcst(g1int_gte<S2Evar(tk(4829))>)(arg0, tmp21)) ;

ATSfunbody_end()
ATSreturn(tmpret20) ;
} /* end of [ATSLIB_056_prelude__gte_g1int_int__7] */
#endif // end of [TEMPLATE]

/*
$(PATSHOME)/prelude/DATS/integer.dats: 12757(line=663, offs=3) -- 12797(line=663, offs=43)
*/
/*
local: 
global: gte_g1int_int$7$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4829)
tmparg = S2Evar(tk(4829))
tmpsub = Some(tk(4829) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__7__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret20__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp21__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12741(line=662, offs=1) -- 12797(line=663, offs=43)
*/
ATSINSflab(__patsflab_gte_g1int_int):
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12784(line=663, offs=30) -- 12795(line=663, offs=41)
*/
ATSINSmove(tmp21__1, atspre_g1int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12766(line=663, offs=12) -- 12797(line=663, offs=43)
*/
ATSINSmove(tmpret20__1, atspre_g1int_gte_int(arg0, tmp21__1)) ;

ATSfunbody_end()
ATSreturn(tmpret20__1) ;
} /* end of [ATSLIB_056_prelude__gte_g1int_int__7__1] */

/*
build/bats_modules/env/src/lib.dats: 4319(line=157, offs=35) -- 4544(line=165, offs=4)
*/
/*
local: 
global: get_cstr$11$0(level=0)
local: 
global: 
*/
ATSextern()
atstype_boxed
build_057_bats_modules_057_env_057_src_057_lib_056_sats__get_cstr(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atsrefarg0_type(atstkind_type(atstype_ptrk)) arg1, atstkind_t0ype(atstype_int) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret24, atstype_boxed) ;
ATStmpdec(tmp25, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp26, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4295(line=157, offs=11) -- 4544(line=165, offs=4)
*/
ATSINSflab(__patsflab_get_cstr):
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4342(line=157, offs=58) -- 4544(line=165, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4359(line=158, offs=14) -- 4487(line=161, offs=13)
*/
ATSINSmove(tmp25, ATSextfcall(_env_getenv, (ATSPMVcastfn(castvwtp1, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), ATSPMVcastfn(castvwtp1, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg1)), arg2))) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4497(line=163, offs=6) -- 4505(line=163, offs=14)
*/
ATSINSmove(tmp26, ATSLIB_056_prelude__gte_g1int_int__7__2(tmp25, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4494(line=163, offs=3) -- 4540(line=164, offs=17)
*/
ATSif(
tmp26
) ATSthen() {
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4511(line=163, offs=20) -- 4522(line=163, offs=31)
*/

/*
#LINCONSTATUS==0
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret24, postiats_tysum_0) ;
#if(0)
ATSINSstore_con1_tag(tmpret24, 0) ;
#endif
ATSINSstore_con1_ofs(tmpret24, postiats_tysum_0, atslab__0, tmp25) ;
ATSINSmove_con1_end()
} ATSelse() {
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4531(line=164, offs=8) -- 4540(line=164, offs=17)
*/

ATSINSmove_nil(tmpret24) ;

} /* ATSendif */
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4342(line=157, offs=58) -- 4544(line=165, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret24) ;
} /* end of [build_057_bats_modules_057_env_057_src_057_lib_056_sats__get_cstr] */

/*
$(PATSHOME)/prelude/DATS/integer.dats: 12757(line=663, offs=3) -- 12797(line=663, offs=43)
*/
/*
local: 
global: gte_g1int_int$7$2(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4829)
tmparg = S2Evar(tk(4829))
tmpsub = Some(tk(4829) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__7__2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret20__2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp21__2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12741(line=662, offs=1) -- 12797(line=663, offs=43)
*/
ATSINSflab(__patsflab_gte_g1int_int):
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12784(line=663, offs=30) -- 12795(line=663, offs=41)
*/
ATSINSmove(tmp21__2, atspre_g1int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12766(line=663, offs=12) -- 12797(line=663, offs=43)
*/
ATSINSmove(tmpret20__2, atspre_g1int_gte_int(arg0, tmp21__2)) ;

ATSfunbody_end()
ATSreturn(tmpret20__2) ;
} /* end of [ATSLIB_056_prelude__gte_g1int_int__7__2] */

/*
build/bats_modules/env/src/lib.dats: 4573(line=167, offs=28) -- 4752(line=173, offs=4)
*/
/*
local: 
global: args_read$13$0(level=0)
local: 
global: 
*/
ATSextern()
atstype_boxed
build_057_bats_modules_057_env_057_src_057_lib_056_sats__args_read(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret29, atstype_boxed) ;
ATStmpdec(tmp30, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp31, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4556(line=167, offs=11) -- 4752(line=173, offs=4)
*/
ATSINSflab(__patsflab_args_read):
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4590(line=167, offs=45) -- 4752(line=173, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4607(line=168, offs=14) -- 4695(line=169, offs=42)
*/
ATSINSmove(tmp30, ATSextfcall(_env_args, (ATSPMVcastfn(castvwtp1, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), arg1))) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4705(line=171, offs=6) -- 4713(line=171, offs=14)
*/
ATSINSmove(tmp31, ATSLIB_056_prelude__gte_g1int_int__7__3(tmp30, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4702(line=171, offs=3) -- 4748(line=172, offs=17)
*/
ATSif(
tmp31
) ATSthen() {
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4719(line=171, offs=20) -- 4730(line=171, offs=31)
*/

/*
#LINCONSTATUS==0
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret29, postiats_tysum_0) ;
#if(0)
ATSINSstore_con1_tag(tmpret29, 0) ;
#endif
ATSINSstore_con1_ofs(tmpret29, postiats_tysum_0, atslab__0, tmp30) ;
ATSINSmove_con1_end()
} ATSelse() {
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4739(line=172, offs=8) -- 4748(line=172, offs=17)
*/

ATSINSmove_nil(tmpret29) ;

} /* ATSendif */
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4590(line=167, offs=45) -- 4752(line=173, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret29) ;
} /* end of [build_057_bats_modules_057_env_057_src_057_lib_056_sats__args_read] */

/*
$(PATSHOME)/prelude/DATS/integer.dats: 12757(line=663, offs=3) -- 12797(line=663, offs=43)
*/
/*
local: 
global: gte_g1int_int$7$3(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4829)
tmparg = S2Evar(tk(4829))
tmpsub = Some(tk(4829) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__7__3(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret20__3, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp21__3, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12741(line=662, offs=1) -- 12797(line=663, offs=43)
*/
ATSINSflab(__patsflab_gte_g1int_int):
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12784(line=663, offs=30) -- 12795(line=663, offs=41)
*/
ATSINSmove(tmp21__3, atspre_g1int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12766(line=663, offs=12) -- 12797(line=663, offs=43)
*/
ATSINSmove(tmpret20__3, atspre_g1int_gte_int(arg0, tmp21__3)) ;

ATSfunbody_end()
ATSreturn(tmpret20__3) ;
} /* end of [ATSLIB_056_prelude__gte_g1int_int__7__3] */

/*
** for initialization(dynloading)
*/
ATSextern()
atsvoid_t0ype
build_057_bats_modules_057_env_057_src_057_lib_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_ext(
build_057_bats_modules_057_env_057_src_057_lib_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
build_057_bats_modules_057_env_057_src_057_lib_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(build_057_bats_modules_057_env_057_src_057_lib_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/* ****** ****** */

/* end-of-compilation-unit */
