/*
**
** The C code is generated by [ATS/Postiats-0-4-1]
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
build/bats_modules/array/src/lib.dats: 2941(line=264, offs=1) -- 3646(line=288, offs=3)
*/

#ifndef _ARR_RUNTIME_DEFINED
#define _ARR_RUNTIME_DEFINED
static inline void
_arr_set_byte(void *p, int off, int v) {
  ((unsigned char *)p)[off] = (unsigned char)v;
}
static inline void
_arr_set_i32(void *p, int off, int v) {
  unsigned char *d = ((unsigned char *)p) + off;
  unsigned int u = (unsigned int)v;
  d[0] = (unsigned char)u;
  d[1] = (unsigned char)(u >> 8);
  d[2] = (unsigned char)(u >> 16);
  d[3] = (unsigned char)(u >> 24);
}
static inline void
_arr_copy_at(void *dst, int off, void *src, int len) {
  unsigned char *d = ((unsigned char *)dst) + off;
  unsigned char *s = (unsigned char *)src;
  int i;
  for (i = 0; i < len; i++) d[i] = s[i];
}
#endif /* _ARR_RUNTIME_DEFINED */
/*
$(PATSHOME)/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
$(PATSHOME)/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
$(PATSHOME)/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
$(PATSHOME)/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
$(PATSHOME)/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
$(PATSHOME)/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstkind_t0ype(atstype_int) atslab__0 ;
} postiats_tysum_0 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(calloc)
ATSdyncst_mac(atspre_g1int_add_int)
ATSdyncst_extfun(build_057_bats_modules_057_array_057_src_057_lib_056_sats__write_borrow, (atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int), atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int)), atsvoid_t0ype) ;
ATSdyncst_extfun(build_057_bats_modules_057_array_057_src_057_lib_056_sats__write_byte, (atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)), atsvoid_t0ype) ;
ATSdyncst_mac(atspre_g1int2int_int_int)
ATSdyncst_mac(atspre_g1int_gte_int)
ATSdyncst_mac(atspre_g0int2int_int_int)
ATSdyncst_mac(atspre_g0int_eq_int)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
/*
build/bats_modules/env/src/lib.dats: 474(line=17, offs=1) -- 3684(line=127, offs=3)
*/
ATSextcode_beg()
#ifndef _ENV_RUNTIME_DEFINED
#define _ENV_RUNTIME_DEFINED
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#if defined(__APPLE__)
#include <crt_externs.h>
#elif defined(__FreeBSD__) || defined(__DragonFly__) || defined(__NetBSD__) || defined(__OpenBSD__)
#include <sys/types.h>
#include <sys/sysctl.h>
#include <unistd.h>
#else
#include <fcntl.h>
#include <unistd.h>
#endif

static int _env_getenv(const char *name, void *buf, int max_len) {
  const char *val = getenv(name);
  if (!val) return -1;
  int len = (int)strlen(val);
  if (len > max_len) len = max_len;
  memcpy(buf, val, (unsigned int)len);
  return len;
}

/* The current directory's absolute path, truncated to max_len bytes;
   -1 when it cannot be determined. */
static int _env_cwd(void *buf, int max_len) {
  char tmp[4096];
  int len;
  if (!getcwd(tmp, sizeof tmp)) return -1;
  len = (int)strlen(tmp);
  if (len > max_len) len = max_len;
  memcpy(buf, tmp, (unsigned int)len);
  return len;
}

/* Whether standard error is a terminal. */
static int _env_stderr_tty(void) {
  return isatty(2) ? 1 : 0;
}

/* Copies argv[0..argc) into buf as NUL-terminated strings back to back,
   stopping at max_len bytes. Returns the byte count. */
static int _env_copy_argv(int argc, char **argv, char *buf, int max_len) {
  int i, k = 0;
  for (i = 0; i < argc && k < max_len; i++) {
    int len = (int)strlen(argv[i]) + 1;
    if (len > max_len - k) len = max_len - k;
    memcpy(buf + k, argv[i], (unsigned int)len);
    k += len;
  }
  return k;
}

/* The process's arguments in the format of Linux's /proc/self/cmdline
   (NUL-terminated strings back to back), truncated to max_len bytes;
   -1 when they cannot be read. */
static int _env_args(void *vbuf, int max_len) {
  char *buf = (char *)vbuf;
#if defined(__APPLE__)
  return _env_copy_argv(*_NSGetArgc(), *_NSGetArgv(), buf, max_len);
#elif defined(__OpenBSD__)
  int mib[4] = { CTL_KERN, KERN_PROC_ARGS, 0, KERN_PROC_ARGV };
  size_t sz = 0;
  char **argv;
  int argc = 0, k;
  mib[2] = (int)getpid();
  if (sysctl(mib, 4, NULL, &sz, NULL, 0) != 0) return -1;
  argv = (char **)malloc(sz);
  if (!argv) return -1;
  if (sysctl(mib, 4, argv, &sz, NULL, 0) != 0) { free(argv); return -1; }
  while (argv[argc]) argc++;
  k = _env_copy_argv(argc, argv, buf, max_len);
  free(argv);
  return k;
#elif defined(__FreeBSD__) || defined(__DragonFly__) || defined(__NetBSD__)
#if defined(__NetBSD__)
  int mib[4] = { CTL_KERN, KERN_PROC_ARGS, 0, KERN_PROC_ARGV };
  int pid_at = 2;
#else
  int mib[4] = { CTL_KERN, KERN_PROC, KERN_PROC_ARGS, 0 };
  int pid_at = 3;
#endif
  size_t sz = 0;
  char *all;
  mib[pid_at] = (int)getpid();
  if (sysctl(mib, 4, NULL, &sz, NULL, 0) != 0) return -1;
  all = (char *)malloc(sz);
  if (!all) return -1;
  if (sysctl(mib, 4, all, &sz, NULL, 0) != 0) { free(all); return -1; }
  if (sz > (size_t)max_len) sz = (size_t)max_len;
  memcpy(buf, all, sz);
  free(all);
  return (int)sz;
#else
  int fd = open("/proc/self/cmdline", O_RDONLY);
  int k = 0;
  if (fd < 0) return -1;
  while (k < max_len) {
    int n = (int)read(fd, buf + k, (unsigned int)(max_len - k));
    if (n <= 0) break;
    k += n;
  }
  close(fd);
  return k;
#endif
}
#endif
ATSextcode_end()
#if(0)
ATSextern()
atstype_boxed
build_057_bats_modules_057_env_057_src_057_lib_056_sats__get(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int), atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
build_057_bats_modules_057_array_057_src_057_lib_056_sats__alloc__1(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_type(atstype_ptrk)
build_057_bats_modules_057_array_057_src_057_lib_056_sats__alloc__1__1(atstkind_t0ype(atstype_int)) ;

#if(0)
ATSstatic()
atstkind_type(atstype_ptrk)
_alloc_zeroed_3__3(atstkind_t0ype(atstype_int)) ;
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_type(atstype_ptrk)
_alloc_zeroed_3__3__1(atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atsvoid_t0ype
build_057_bats_modules_057_array_057_src_057_lib_056_sats__free__6(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atsvoid_t0ype
build_057_bats_modules_057_array_057_src_057_lib_056_sats__free__6__1(atstkind_type(atstype_ptrk)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__8(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__8__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atstype_boxed
build_057_bats_modules_057_env_057_src_057_lib_056_sats__get_cstr(atsrefarg0_type(atstkind_type(atstype_ptrk)), atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__8__2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atstype_boxed
build_057_bats_modules_057_env_057_src_057_lib_056_sats__args_read(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__8__3(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atstype_boxed
build_057_bats_modules_057_env_057_src_057_lib_056_sats__cwd_read(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__8__4(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
build_057_bats_modules_057_env_057_src_057_lib_056_sats__stderr_is_terminal() ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__19(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__19__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

/*
build/bats_modules/env/src/lib.dats: 4547(line=171, offs=30) -- 4956(line=183, offs=4)
*/
/*
local: 
global: get$0$0(level=0)
local: 
global: 
*/
ATSextern()
atstype_boxed
build_057_bats_modules_057_env_057_src_057_lib_056_sats__get(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_t0ype(atstype_int) arg1, atsrefarg0_type(atstkind_type(atstype_ptrk)) arg2, atstkind_t0ype(atstype_int) arg3)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstype_boxed) ;
ATStmpdec(tmp1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp6, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp7) ;
// ATStmpdec_void(tmp8) ;
ATStmpdec(tmp9, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp10) ;
ATStmpdec(tmp13, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4528(line=171, offs=11) -- 4956(line=183, offs=4)
*/
ATSINSflab(__patsflab_get):
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4580(line=171, offs=63) -- 4956(line=183, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4613(line=172, offs=30) -- 4625(line=172, offs=42)
*/
ATSINSmove(tmp6, atspre_g1int_add_int(arg1, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4598(line=172, offs=15) -- 4626(line=172, offs=43)
*/
ATSINSmove(tmp1, build_057_bats_modules_057_array_057_src_057_lib_056_sats__alloc__1__1(tmp6)) ;

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4638(line=173, offs=12) -- 4679(line=173, offs=53)
*/
ATSINSmove_void(tmp7, build_057_bats_modules_057_array_057_src_057_lib_056_sats__write_borrow(ATSPMVrefarg0(tmp1), ATSPMVi0nt(0), ATSPMVrefarg0(arg0), arg1)) ;

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4691(line=174, offs=12) -- 4724(line=174, offs=45)
*/
ATSINSmove_void(tmp8, build_057_bats_modules_057_array_057_src_057_lib_056_sats__write_byte(ATSPMVrefarg0(tmp1), arg1, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4738(line=175, offs=14) -- 4867(line=178, offs=13)
*/
ATSINSmove(tmp9, ATSextfcall(_env_getenv, (ATSPMVcastfn(castvwtp1, atstkind_type(atstype_ptrk), ATSPMVrefarg0(tmp1)), ATSPMVcastfn(castvwtp1, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg2)), arg3))) ;
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4880(line=179, offs=12) -- 4899(line=179, offs=31)
*/
ATSINSmove_void(tmp10, build_057_bats_modules_057_array_057_src_057_lib_056_sats__free__6__1(tmp1)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4909(line=181, offs=6) -- 4917(line=181, offs=14)
*/
ATSINSmove(tmp13, ATSLIB_056_prelude__gte_g1int_int__8__1(tmp9, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4906(line=181, offs=3) -- 4952(line=182, offs=17)
*/
ATSif(
tmp13
) ATSthen() {
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4923(line=181, offs=20) -- 4934(line=181, offs=31)
*/

/*
#LINCONSTATUS==0
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret0, postiats_tysum_0) ;
#if(0)
ATSINSstore_con1_tag(tmpret0, 0) ;
#endif
ATSINSstore_con1_ofs(tmpret0, postiats_tysum_0, atslab__0, tmp9) ;
ATSINSmove_con1_end()
} ATSelse() {
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4943(line=182, offs=8) -- 4952(line=182, offs=17)
*/

ATSINSmove_nil(tmpret0) ;

} /* ATSendif */
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4580(line=171, offs=63) -- 4956(line=183, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [build_057_bats_modules_057_env_057_src_057_lib_056_sats__get] */

#if(0)
/*
build/bats_modules/array/src/lib.dats: 4509(line=321, offs=22) -- 4536(line=321, offs=49)
*/
/*
local: 
global: alloc$1$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = 
tmparg = S2Ecst(byte_t0ype)
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
build_057_bats_modules_057_array_057_src_057_lib_056_sats__alloc__1(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4498(line=321, offs=11) -- 4537(line=321, offs=50)
*/
ATSINSflab(__patsflab_alloc):
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4515(line=321, offs=28) -- 4536(line=321, offs=49)
*/
ATSINSmove(tmpret2, PMVtmpltvar(_alloc_zeroed$4739(0)<S2Ecst(byte_t0ype)>)(arg0)) ;

ATSfunbody_end()
ATSreturn(tmpret2) ;
} /* end of [build_057_bats_modules_057_array_057_src_057_lib_056_sats__alloc__1] */
#endif // end of [TEMPLATE]

/*
build/bats_modules/array/src/lib.dats: 4509(line=321, offs=22) -- 4536(line=321, offs=49)
*/
/*
local: 
global: alloc$1$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = 
tmparg = S2Ecst(byte_t0ype)
tmpsub = Some()
*/
atstkind_type(atstype_ptrk)
build_057_bats_modules_057_array_057_src_057_lib_056_sats__alloc__1__1(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2__1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4498(line=321, offs=11) -- 4537(line=321, offs=50)
*/
ATSINSflab(__patsflab_alloc):
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4515(line=321, offs=28) -- 4536(line=321, offs=49)
*/
ATSINSmove(tmpret2__1, _alloc_zeroed_3__3__1(arg0)) ;

ATSfunbody_end()
ATSreturn(tmpret2__1) ;
} /* end of [build_057_bats_modules_057_array_057_src_057_lib_056_sats__alloc__1__1] */

#if(0)
/*
build/bats_modules/array/src/lib.dats: 4413(line=318, offs=13) -- 4486(line=319, offs=24)
*/
/*
local: 
global: _alloc_zeroed_3$0(level=2)
local: 
global: 
*/
ATSstatic()
atstkind_type(atstype_ptrk)
_alloc_zeroed_3__3(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret4, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4413(line=318, offs=13) -- 4486(line=319, offs=24)
*/
ATSINSflab(__patsflab__alloc_zeroed_3):
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4465(line=319, offs=3) -- 4486(line=319, offs=24)
*/
ATSINSmove(tmpret4, calloc(arg0, ATSPMVsizeof(atstyvar_type(a)))) ;

ATSfunbody_end()
ATSreturn(tmpret4) ;
} /* end of [_alloc_zeroed_3__3] */
#endif // end of [TEMPLATE]

/*
build/bats_modules/array/src/lib.dats: 4413(line=318, offs=13) -- 4486(line=319, offs=24)
*/
/*
local: 
global: _alloc_zeroed_3$1(level=2)
local: 
global: 
*/
ATSstatic()
atstkind_type(atstype_ptrk)
_alloc_zeroed_3__3__1(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret4__1, atstkind_type(atstype_ptrk)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4413(line=318, offs=13) -- 4486(line=319, offs=24)
*/
ATSINSflab(__patsflab__alloc_zeroed_3):
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4465(line=319, offs=3) -- 4486(line=319, offs=24)
*/
ATSINSmove(tmpret4__1, calloc(arg0, ATSPMVsizeof(atstkind_t0ype(atstype_byte)))) ;

ATSfunbody_end()
ATSreturn(tmpret4__1) ;
} /* end of [_alloc_zeroed_3__3__1] */

#if(0)
/*
build/bats_modules/array/src/lib.dats: 4808(line=329, offs=11) -- 4847(line=330, offs=32)
*/
/*
local: 
global: free$6$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8667)
tmparg = S2Evar(a(8667))
tmpsub = None()
*/
atsvoid_t0ype
build_057_bats_modules_057_array_057_src_057_lib_056_sats__free__6(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret11) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4798(line=329, offs=1) -- 4847(line=330, offs=32)
*/
ATSINSflab(__patsflab_free):
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4819(line=330, offs=4) -- 4847(line=330, offs=32)
*/
ATSINSmove_void(tmpret11, ATSextfcall(free, (arg0))) ;
ATSfunbody_end()
ATSreturn_void(tmpret11) ;
} /* end of [build_057_bats_modules_057_array_057_src_057_lib_056_sats__free__6] */
#endif // end of [TEMPLATE]

/*
build/bats_modules/array/src/lib.dats: 4808(line=329, offs=11) -- 4847(line=330, offs=32)
*/
/*
local: 
global: free$6$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = a(8667)
tmparg = S2Evar(a(8667))
tmpsub = Some(a(8667) -> S2Ecst(byte_t0ype))
*/
atsvoid_t0ype
build_057_bats_modules_057_array_057_src_057_lib_056_sats__free__6__1(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret11__1) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4798(line=329, offs=1) -- 4847(line=330, offs=32)
*/
ATSINSflab(__patsflab_free):
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4819(line=330, offs=4) -- 4847(line=330, offs=32)
*/
ATSINSmove_void(tmpret11__1, ATSextfcall(free, (arg0))) ;
ATSfunbody_end()
ATSreturn_void(tmpret11__1) ;
} /* end of [build_057_bats_modules_057_array_057_src_057_lib_056_sats__free__6__1] */

#if(0)
/*
$(PATSHOME)/prelude/DATS/integer.dats: 12757(line=663, offs=3) -- 12797(line=663, offs=43)
*/
/*
local: 
global: gte_g1int_int$8$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4802)
tmparg = S2Evar(tk(4802))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__8(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret14, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp15, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12741(line=662, offs=1) -- 12797(line=663, offs=43)
*/
ATSINSflab(__patsflab_gte_g1int_int):
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12784(line=663, offs=30) -- 12795(line=663, offs=41)
*/
ATSINSmove(tmp15, PMVtmpltcst(g1int2int<S2Eextkind(atstype_int), S2Evar(tk(4802))>)(arg1)) ;

/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12766(line=663, offs=12) -- 12797(line=663, offs=43)
*/
ATSINSmove(tmpret14, PMVtmpltcst(g1int_gte<S2Evar(tk(4802))>)(arg0, tmp15)) ;

ATSfunbody_end()
ATSreturn(tmpret14) ;
} /* end of [ATSLIB_056_prelude__gte_g1int_int__8] */
#endif // end of [TEMPLATE]

/*
$(PATSHOME)/prelude/DATS/integer.dats: 12757(line=663, offs=3) -- 12797(line=663, offs=43)
*/
/*
local: 
global: gte_g1int_int$8$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4802)
tmparg = S2Evar(tk(4802))
tmpsub = Some(tk(4802) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__8__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret14__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp15__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12741(line=662, offs=1) -- 12797(line=663, offs=43)
*/
ATSINSflab(__patsflab_gte_g1int_int):
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12784(line=663, offs=30) -- 12795(line=663, offs=41)
*/
ATSINSmove(tmp15__1, atspre_g1int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12766(line=663, offs=12) -- 12797(line=663, offs=43)
*/
ATSINSmove(tmpret14__1, atspre_g1int_gte_int(arg0, tmp15__1)) ;

ATSfunbody_end()
ATSreturn(tmpret14__1) ;
} /* end of [ATSLIB_056_prelude__gte_g1int_int__8__1] */

/*
build/bats_modules/env/src/lib.dats: 4992(line=185, offs=35) -- 5217(line=193, offs=4)
*/
/*
local: 
global: get_cstr$12$0(level=0)
local: 
global: 
*/
ATSextern()
atstype_boxed
build_057_bats_modules_057_env_057_src_057_lib_056_sats__get_cstr(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atsrefarg0_type(atstkind_type(atstype_ptrk)) arg1, atstkind_t0ype(atstype_int) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret18, atstype_boxed) ;
ATStmpdec(tmp19, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp20, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 4968(line=185, offs=11) -- 5217(line=193, offs=4)
*/
ATSINSflab(__patsflab_get_cstr):
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 5015(line=185, offs=58) -- 5217(line=193, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 5032(line=186, offs=14) -- 5160(line=189, offs=13)
*/
ATSINSmove(tmp19, ATSextfcall(_env_getenv, (ATSPMVcastfn(castvwtp1, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), ATSPMVcastfn(castvwtp1, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg1)), arg2))) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 5170(line=191, offs=6) -- 5178(line=191, offs=14)
*/
ATSINSmove(tmp20, ATSLIB_056_prelude__gte_g1int_int__8__2(tmp19, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 5167(line=191, offs=3) -- 5213(line=192, offs=17)
*/
ATSif(
tmp20
) ATSthen() {
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 5184(line=191, offs=20) -- 5195(line=191, offs=31)
*/

/*
#LINCONSTATUS==0
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret18, postiats_tysum_0) ;
#if(0)
ATSINSstore_con1_tag(tmpret18, 0) ;
#endif
ATSINSstore_con1_ofs(tmpret18, postiats_tysum_0, atslab__0, tmp19) ;
ATSINSmove_con1_end()
} ATSelse() {
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 5204(line=192, offs=8) -- 5213(line=192, offs=17)
*/

ATSINSmove_nil(tmpret18) ;

} /* ATSendif */
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 5015(line=185, offs=58) -- 5217(line=193, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret18) ;
} /* end of [build_057_bats_modules_057_env_057_src_057_lib_056_sats__get_cstr] */

/*
$(PATSHOME)/prelude/DATS/integer.dats: 12757(line=663, offs=3) -- 12797(line=663, offs=43)
*/
/*
local: 
global: gte_g1int_int$8$2(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4802)
tmparg = S2Evar(tk(4802))
tmpsub = Some(tk(4802) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__8__2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret14__2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp15__2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12741(line=662, offs=1) -- 12797(line=663, offs=43)
*/
ATSINSflab(__patsflab_gte_g1int_int):
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12784(line=663, offs=30) -- 12795(line=663, offs=41)
*/
ATSINSmove(tmp15__2, atspre_g1int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12766(line=663, offs=12) -- 12797(line=663, offs=43)
*/
ATSINSmove(tmpret14__2, atspre_g1int_gte_int(arg0, tmp15__2)) ;

ATSfunbody_end()
ATSreturn(tmpret14__2) ;
} /* end of [ATSLIB_056_prelude__gte_g1int_int__8__2] */

/*
build/bats_modules/env/src/lib.dats: 5246(line=195, offs=28) -- 5425(line=201, offs=4)
*/
/*
local: 
global: args_read$14$0(level=0)
local: 
global: 
*/
ATSextern()
atstype_boxed
build_057_bats_modules_057_env_057_src_057_lib_056_sats__args_read(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret23, atstype_boxed) ;
ATStmpdec(tmp24, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp25, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 5229(line=195, offs=11) -- 5425(line=201, offs=4)
*/
ATSINSflab(__patsflab_args_read):
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 5263(line=195, offs=45) -- 5425(line=201, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 5280(line=196, offs=14) -- 5368(line=197, offs=42)
*/
ATSINSmove(tmp24, ATSextfcall(_env_args, (ATSPMVcastfn(castvwtp1, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), arg1))) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 5378(line=199, offs=6) -- 5386(line=199, offs=14)
*/
ATSINSmove(tmp25, ATSLIB_056_prelude__gte_g1int_int__8__3(tmp24, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 5375(line=199, offs=3) -- 5421(line=200, offs=17)
*/
ATSif(
tmp25
) ATSthen() {
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 5392(line=199, offs=20) -- 5403(line=199, offs=31)
*/

/*
#LINCONSTATUS==0
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret23, postiats_tysum_0) ;
#if(0)
ATSINSstore_con1_tag(tmpret23, 0) ;
#endif
ATSINSstore_con1_ofs(tmpret23, postiats_tysum_0, atslab__0, tmp24) ;
ATSINSmove_con1_end()
} ATSelse() {
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 5412(line=200, offs=8) -- 5421(line=200, offs=17)
*/

ATSINSmove_nil(tmpret23) ;

} /* ATSendif */
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 5263(line=195, offs=45) -- 5425(line=201, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret23) ;
} /* end of [build_057_bats_modules_057_env_057_src_057_lib_056_sats__args_read] */

/*
$(PATSHOME)/prelude/DATS/integer.dats: 12757(line=663, offs=3) -- 12797(line=663, offs=43)
*/
/*
local: 
global: gte_g1int_int$8$3(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4802)
tmparg = S2Evar(tk(4802))
tmpsub = Some(tk(4802) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__8__3(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret14__3, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp15__3, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12741(line=662, offs=1) -- 12797(line=663, offs=43)
*/
ATSINSflab(__patsflab_gte_g1int_int):
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12784(line=663, offs=30) -- 12795(line=663, offs=41)
*/
ATSINSmove(tmp15__3, atspre_g1int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12766(line=663, offs=12) -- 12797(line=663, offs=43)
*/
ATSINSmove(tmpret14__3, atspre_g1int_gte_int(arg0, tmp15__3)) ;

ATSfunbody_end()
ATSreturn(tmpret14__3) ;
} /* end of [ATSLIB_056_prelude__gte_g1int_int__8__3] */

/*
build/bats_modules/env/src/lib.dats: 5453(line=203, offs=27) -- 5631(line=209, offs=4)
*/
/*
local: 
global: cwd_read$16$0(level=0)
local: 
global: 
*/
ATSextern()
atstype_boxed
build_057_bats_modules_057_env_057_src_057_lib_056_sats__cwd_read(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret28, atstype_boxed) ;
ATStmpdec(tmp29, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp30, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 5437(line=203, offs=11) -- 5631(line=209, offs=4)
*/
ATSINSflab(__patsflab_cwd_read):
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 5470(line=203, offs=44) -- 5631(line=209, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 5487(line=204, offs=14) -- 5574(line=205, offs=42)
*/
ATSINSmove(tmp29, ATSextfcall(_env_cwd, (ATSPMVcastfn(castvwtp1, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), arg1))) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 5584(line=207, offs=6) -- 5592(line=207, offs=14)
*/
ATSINSmove(tmp30, ATSLIB_056_prelude__gte_g1int_int__8__4(tmp29, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 5581(line=207, offs=3) -- 5627(line=208, offs=17)
*/
ATSif(
tmp30
) ATSthen() {
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 5598(line=207, offs=20) -- 5609(line=207, offs=31)
*/

/*
#LINCONSTATUS==0
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret28, postiats_tysum_0) ;
#if(0)
ATSINSstore_con1_tag(tmpret28, 0) ;
#endif
ATSINSstore_con1_ofs(tmpret28, postiats_tysum_0, atslab__0, tmp29) ;
ATSINSmove_con1_end()
} ATSelse() {
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 5618(line=208, offs=8) -- 5627(line=208, offs=17)
*/

ATSINSmove_nil(tmpret28) ;

} /* ATSendif */
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 5470(line=203, offs=44) -- 5631(line=209, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret28) ;
} /* end of [build_057_bats_modules_057_env_057_src_057_lib_056_sats__cwd_read] */

/*
$(PATSHOME)/prelude/DATS/integer.dats: 12757(line=663, offs=3) -- 12797(line=663, offs=43)
*/
/*
local: 
global: gte_g1int_int$8$4(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4802)
tmparg = S2Evar(tk(4802))
tmpsub = Some(tk(4802) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g1int_int__8__4(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret14__4, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp15__4, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12741(line=662, offs=1) -- 12797(line=663, offs=43)
*/
ATSINSflab(__patsflab_gte_g1int_int):
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12784(line=663, offs=30) -- 12795(line=663, offs=41)
*/
ATSINSmove(tmp15__4, atspre_g1int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12766(line=663, offs=12) -- 12797(line=663, offs=43)
*/
ATSINSmove(tmpret14__4, atspre_g1int_gte_int(arg0, tmp15__4)) ;

ATSfunbody_end()
ATSreturn(tmpret14__4) ;
} /* end of [ATSLIB_056_prelude__gte_g1int_int__8__4] */

/*
build/bats_modules/env/src/lib.dats: 5662(line=211, offs=30) -- 5708(line=212, offs=42)
*/
/*
local: 
global: stderr_is_terminal$18$0(level=0)
local: 
global: 
*/
ATSextern()
atstkind_t0ype(atstype_bool)
build_057_bats_modules_057_env_057_src_057_lib_056_sats__stderr_is_terminal()
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret33, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp38, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 5643(line=211, offs=11) -- 5708(line=212, offs=42)
*/
ATSINSflab(__patsflab_stderr_is_terminal):
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 5670(line=212, offs=4) -- 5703(line=212, offs=37)
*/
ATSINSmove(tmp38, ATSextfcall(_env_stderr_tty, ())) ;
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 5670(line=212, offs=4) -- 5708(line=212, offs=42)
*/
ATSINSmove(tmpret33, ATSLIB_056_prelude__eq_g0int_int__19__1(tmp38, ATSPMVi0nt(1))) ;

ATSfunbody_end()
ATSreturn(tmpret33) ;
} /* end of [build_057_bats_modules_057_env_057_src_057_lib_056_sats__stderr_is_terminal] */

#if(0)
/*
$(PATSHOME)/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$19$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4790)
tmparg = S2Evar(tk(4790))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__19(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret34, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp35, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp35, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4790))>)(arg1)) ;

/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret34, PMVtmpltcst(g0int_eq<S2Evar(tk(4790))>)(arg0, tmp35)) ;

ATSfunbody_end()
ATSreturn(tmpret34) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__19] */
#endif // end of [TEMPLATE]

/*
$(PATSHOME)/prelude/DATS/integer.dats: 12259(line=635, offs=3) -- 12298(line=635, offs=42)
*/
/*
local: 
global: eq_g0int_int$19$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4790)
tmparg = S2Evar(tk(4790))
tmpsub = Some(tk(4790) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__19__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret34__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp35__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12244(line=634, offs=1) -- 12298(line=635, offs=42)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12285(line=635, offs=29) -- 12296(line=635, offs=40)
*/
ATSINSmove(tmp35__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12268(line=635, offs=12) -- 12298(line=635, offs=42)
*/
ATSINSmove(tmpret34__1, atspre_g0int_eq_int(arg0, tmp35__1)) ;

ATSfunbody_end()
ATSreturn(tmpret34__1) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__19__1] */

/*
** for initialization(dynloading)
*/
ATSextern()
atsvoid_t0ype
build_057_bats_modules_057_env_057_src_057_lib_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_ext(
build_057_bats_modules_057_env_057_src_057_lib_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
build_057_bats_modules_057_env_057_src_057_lib_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(build_057_bats_modules_057_env_057_src_057_lib_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/* ****** ****** */

/* end-of-compilation-unit */
