/*
**
** The C code is generated by [ATS/Postiats-0-4-1]
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
build/bats_modules/array/src/lib.dats: 2974(line=306, offs=1) -- 4118(line=351, offs=3)
*/

#ifndef _ARR_RUNTIME_DEFINED
#define _ARR_RUNTIME_DEFINED
static inline void
_arr_set_byte(void *p, int off, int v) {
  ((unsigned char *)p)[off] = (unsigned char)v;
}
static inline void
_arr_set_i32(void *p, int off, int v) {
  *(int *)(((char *)p) + off) = v;
}
static inline void
_arr_copy_at(void *dst, int off, void *src, int len) {
  unsigned char *d = ((unsigned char *)dst) + off;
  unsigned char *s = (unsigned char *)src;
  int i;
  for (i = 0; i < len; i++) d[i] = s[i];
}

typedef struct { char *base; int used; int max_sz; } _arr_arena_t;

static inline void *
_arr_arena_create(int max_sz) {
  _arr_arena_t *a;
  a = (void *)malloc(sizeof(_arr_arena_t));
  a->base = (char *)malloc(max_sz);
  a->used = 0;
  a->max_sz = max_sz;
  memset(a->base, 0, max_sz);
  return (void *)a;
}
static inline void *
_arr_arena_alloc(void *arena, int sz) {
  _arr_arena_t *a = (_arr_arena_t *)arena;
  void *p = (void *)(a->base + a->used);
  a->used += sz;
  return p;
}
static inline void
_arr_arena_destroy(void *arena) {
  _arr_arena_t *a = (_arr_arena_t *)arena;
  free(a->base);
  free((void *)a);
}
#endif /* _ARR_RUNTIME_DEFINED */
/*
$(PATSHOME)/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
$(PATSHOME)/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
$(PATSHOME)/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
$(PATSHOME)/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
$(PATSHOME)/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
$(PATSHOME)/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
#if(0)
int contag ;
#endif
atstkind_t0ype(atstype_int) atslab__0 ;
} postiats_tysum_0 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_g1uint2int_size_int)
ATSdyncst_mac(malloc)
ATSdyncst_mac(atspre_g1int_mul_int)
ATSdyncst_mac(atspre_g1int_add_int)
ATSdyncst_extfun(build_057_bats_modules_057_array_057_src_057_lib_056_sats__write_borrow, (atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int), atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int)), atsvoid_t0ype) ;
ATSdyncst_extfun(build_057_bats_modules_057_array_057_src_057_lib_056_sats__write_byte, (atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)), atsvoid_t0ype) ;
ATSdyncst_mac(atspre_g0int2int_int_int)
ATSdyncst_mac(atspre_g0int_gte_int)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
/*
build/bats_modules/env/src/lib.dats: 474(line=17, offs=1) -- 831(line=32, offs=3)
*/
ATSextcode_beg()
#ifndef _ENV_RUNTIME_DEFINED
#define _ENV_RUNTIME_DEFINED
#include <stdlib.h>
#include <string.h>

static int _env_getenv(const char *name, void *buf, int max_len) {
  const char *val = getenv(name);
  if (!val) return -1;
  int len = (int)strlen(val);
  if (len > max_len) len = max_len;
  memcpy(buf, val, (unsigned int)len);
  return len;
}
#endif
ATSextcode_end()
#if(0)
ATSextern()
atstype_boxed
build_057_bats_modules_057_env_057_src_057_lib_056_sats__get(atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int), atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSextern()
atstkind_type(atstype_ptrk)
build_057_bats_modules_057_array_057_src_057_lib_056_sats__alloc__1(atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_type(atstype_ptrk)
build_057_bats_modules_057_array_057_src_057_lib_056_sats__alloc__1__1(atstkind_t0ype(atstype_int)) ;

#if(0)
#if(0)
ATSextern()
atsvoid_t0ype
build_057_bats_modules_057_array_057_src_057_lib_056_sats__free__5(atstkind_type(atstype_ptrk)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atsvoid_t0ype
build_057_bats_modules_057_array_057_src_057_lib_056_sats__free__5__1(atstkind_type(atstype_ptrk)) ;

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g0int_int__7(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g0int_int__7__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atstype_boxed
build_057_bats_modules_057_env_057_src_057_lib_056_sats__get_cstr(atsrefarg0_type(atstkind_type(atstype_ptrk)), atsrefarg0_type(atstkind_type(atstype_ptrk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g0int_int__7__2(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

/*
build/bats_modules/env/src/lib.dats: 1172(line=56, offs=30) -- 1562(line=68, offs=4)
*/
/*
local: 
global: get$0$0(level=0)
local: 
global: 
*/
ATSextern()
atstype_boxed
build_057_bats_modules_057_env_057_src_057_lib_056_sats__get(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atstkind_t0ype(atstype_int) arg1, atsrefarg0_type(atstkind_type(atstype_ptrk)) arg2, atstkind_t0ype(atstype_int) arg3)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret0, atstype_boxed) ;
ATStmpdec(tmp1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp12, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp13) ;
// ATStmpdec_void(tmp14) ;
ATStmpdec(tmp15, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp16) ;
ATStmpdec(tmp19, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 1153(line=56, offs=11) -- 1562(line=68, offs=4)
*/
ATSINSflab(__patsflab_get):
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 1205(line=56, offs=63) -- 1562(line=68, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 1238(line=57, offs=30) -- 1250(line=57, offs=42)
*/
ATSINSmove(tmp12, atspre_g1int_add_int(arg1, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 1223(line=57, offs=15) -- 1251(line=57, offs=43)
*/
ATSINSmove(tmp1, build_057_bats_modules_057_array_057_src_057_lib_056_sats__alloc__1__1(tmp12)) ;

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 1263(line=58, offs=12) -- 1304(line=58, offs=53)
*/
ATSINSmove_void(tmp13, build_057_bats_modules_057_array_057_src_057_lib_056_sats__write_borrow(ATSPMVrefarg0(tmp1), ATSPMVi0nt(0), ATSPMVrefarg0(arg0), arg1)) ;

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 1316(line=59, offs=12) -- 1349(line=59, offs=45)
*/
ATSINSmove_void(tmp14, build_057_bats_modules_057_array_057_src_057_lib_056_sats__write_byte(ATSPMVrefarg0(tmp1), arg1, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 1363(line=60, offs=14) -- 1473(line=63, offs=13)
*/
ATSINSmove(tmp15, ATSextfcall(_env_getenv, (ATSPMVcastfn(castvwtp1, atstkind_type(atstype_ptrk), ATSPMVrefarg0(tmp1)), ATSPMVcastfn(castvwtp1, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg2)), arg3))) ;
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 1486(line=64, offs=12) -- 1505(line=64, offs=31)
*/
ATSINSmove_void(tmp16, build_057_bats_modules_057_array_057_src_057_lib_056_sats__free__5__1(tmp1)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 1515(line=66, offs=6) -- 1523(line=66, offs=14)
*/
ATSINSmove(tmp19, ATSLIB_056_prelude__gte_g0int_int__7__1(tmp15, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 1512(line=66, offs=3) -- 1558(line=67, offs=17)
*/
ATSif(
tmp19
) ATSthen() {
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 1529(line=66, offs=20) -- 1540(line=66, offs=31)
*/

/*
#LINCONSTATUS==0
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret0, postiats_tysum_0) ;
#if(0)
ATSINSstore_con1_tag(tmpret0, 0) ;
#endif
ATSINSstore_con1_ofs(tmpret0, postiats_tysum_0, atslab__0, tmp15) ;
ATSINSmove_con1_end()
} ATSelse() {
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 1549(line=67, offs=8) -- 1558(line=67, offs=17)
*/

ATSINSmove_nil(tmpret0) ;

} /* ATSendif */
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 1205(line=56, offs=63) -- 1562(line=68, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret0) ;
} /* end of [build_057_bats_modules_057_env_057_src_057_lib_056_sats__get] */

#if(0)
/*
build/bats_modules/array/src/lib.dats: 4755(line=380, offs=9) -- 4895(line=386, offs=4)
*/
/*
local: 
global: alloc$1$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8679)
tmparg = S2Evar(a(8679))
tmpsub = None()
*/
atstkind_type(atstype_ptrk)
build_057_bats_modules_057_array_057_src_057_lib_056_sats__alloc__1(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp3, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp4, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp5, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp6) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4747(line=380, offs=1) -- 4895(line=386, offs=4)
*/
ATSINSflab(__patsflab_alloc):
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4761(line=380, offs=15) -- 4895(line=386, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4784(line=381, offs=20) -- 4799(line=381, offs=35)
*/
ATSINSmove(tmp4, atspre_g1uint2int_size_int(ATSPMVsizeof(atstyvar_type(a)))) ;

/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4780(line=381, offs=16) -- 4799(line=381, offs=35)
*/
ATSINSmove(tmp3, PMVtmpltcst(g1int_mul<S2Eextkind(atstype_int)>)(arg0, tmp4)) ;

/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4810(line=382, offs=11) -- 4830(line=382, offs=31)
*/
ATSINSmove(tmp5, malloc(tmp3)) ;

/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4844(line=383, offs=13) -- 4883(line=383, offs=52)
*/
ATSINSmove_void(tmp6, ATSextfcall(memset, (tmp5, ATSPMVi0nt(0), tmp3))) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4890(line=385, offs=3) -- 4891(line=385, offs=4)
*/
ATSINSmove(tmpret2, tmp5) ;
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4761(line=380, offs=15) -- 4895(line=386, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret2) ;
} /* end of [build_057_bats_modules_057_array_057_src_057_lib_056_sats__alloc__1] */
#endif // end of [TEMPLATE]

/*
build/bats_modules/array/src/lib.dats: 4755(line=380, offs=9) -- 4895(line=386, offs=4)
*/
/*
local: 
global: alloc$1$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = a(8679)
tmparg = S2Evar(a(8679))
tmpsub = Some(a(8679) -> S2Ecst(byte_t0ype))
*/
atstkind_type(atstype_ptrk)
build_057_bats_modules_057_array_057_src_057_lib_056_sats__alloc__1__1(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret2__1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp3__1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp4__1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp5__1, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp6__1) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4747(line=380, offs=1) -- 4895(line=386, offs=4)
*/
ATSINSflab(__patsflab_alloc):
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4761(line=380, offs=15) -- 4895(line=386, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4784(line=381, offs=20) -- 4799(line=381, offs=35)
*/
ATSINSmove(tmp4__1, atspre_g1uint2int_size_int(ATSPMVsizeof(atstkind_t0ype(atstype_byte)))) ;

/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4780(line=381, offs=16) -- 4799(line=381, offs=35)
*/
ATSINSmove(tmp3__1, atspre_g1int_mul_int(arg0, tmp4__1)) ;

/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4810(line=382, offs=11) -- 4830(line=382, offs=31)
*/
ATSINSmove(tmp5__1, malloc(tmp3__1)) ;

/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4844(line=383, offs=13) -- 4883(line=383, offs=52)
*/
ATSINSmove_void(tmp6__1, ATSextfcall(memset, (tmp5__1, ATSPMVi0nt(0), tmp3__1))) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4890(line=385, offs=3) -- 4891(line=385, offs=4)
*/
ATSINSmove(tmpret2__1, tmp5__1) ;
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4761(line=380, offs=15) -- 4895(line=386, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret2__1) ;
} /* end of [build_057_bats_modules_057_array_057_src_057_lib_056_sats__alloc__1__1] */

#if(0)
/*
build/bats_modules/array/src/lib.dats: 4920(line=389, offs=11) -- 4959(line=390, offs=32)
*/
/*
local: 
global: free$5$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = a(8684)
tmparg = S2Evar(a(8684))
tmpsub = None()
*/
atsvoid_t0ype
build_057_bats_modules_057_array_057_src_057_lib_056_sats__free__5(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret17) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4910(line=389, offs=1) -- 4959(line=390, offs=32)
*/
ATSINSflab(__patsflab_free):
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4931(line=390, offs=4) -- 4959(line=390, offs=32)
*/
ATSINSmove_void(tmpret17, ATSextfcall(free, (arg0))) ;
ATSfunbody_end()
ATSreturn_void(tmpret17) ;
} /* end of [build_057_bats_modules_057_array_057_src_057_lib_056_sats__free__5] */
#endif // end of [TEMPLATE]

/*
build/bats_modules/array/src/lib.dats: 4920(line=389, offs=11) -- 4959(line=390, offs=32)
*/
/*
local: 
global: free$5$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = a(8684)
tmparg = S2Evar(a(8684))
tmpsub = Some(a(8684) -> S2Ecst(byte_t0ype))
*/
atsvoid_t0ype
build_057_bats_modules_057_array_057_src_057_lib_056_sats__free__5__1(atstkind_type(atstype_ptrk) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret17__1) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4910(line=389, offs=1) -- 4959(line=390, offs=32)
*/
ATSINSflab(__patsflab_free):
/*
emit_instr: loc0 = build/bats_modules/array/src/lib.dats: 4931(line=390, offs=4) -- 4959(line=390, offs=32)
*/
ATSINSmove_void(tmpret17__1, ATSextfcall(free, (arg0))) ;
ATSfunbody_end()
ATSreturn_void(tmpret17__1) ;
} /* end of [build_057_bats_modules_057_array_057_src_057_lib_056_sats__free__5__1] */

#if(0)
/*
$(PATSHOME)/prelude/DATS/integer.dats: 12178(line=630, offs=3) -- 12218(line=630, offs=43)
*/
/*
local: 
global: gte_g0int_int$7$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4811)
tmparg = S2Evar(tk(4811))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g0int_int__7(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret20, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp21, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12162(line=629, offs=1) -- 12218(line=630, offs=43)
*/
ATSINSflab(__patsflab_gte_g0int_int):
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12205(line=630, offs=30) -- 12216(line=630, offs=41)
*/
ATSINSmove(tmp21, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4811))>)(arg1)) ;

/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12187(line=630, offs=12) -- 12218(line=630, offs=43)
*/
ATSINSmove(tmpret20, PMVtmpltcst(g0int_gte<S2Evar(tk(4811))>)(arg0, tmp21)) ;

ATSfunbody_end()
ATSreturn(tmpret20) ;
} /* end of [ATSLIB_056_prelude__gte_g0int_int__7] */
#endif // end of [TEMPLATE]

/*
$(PATSHOME)/prelude/DATS/integer.dats: 12178(line=630, offs=3) -- 12218(line=630, offs=43)
*/
/*
local: 
global: gte_g0int_int$7$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4811)
tmparg = S2Evar(tk(4811))
tmpsub = Some(tk(4811) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g0int_int__7__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret20__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp21__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12162(line=629, offs=1) -- 12218(line=630, offs=43)
*/
ATSINSflab(__patsflab_gte_g0int_int):
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12205(line=630, offs=30) -- 12216(line=630, offs=41)
*/
ATSINSmove(tmp21__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12187(line=630, offs=12) -- 12218(line=630, offs=43)
*/
ATSINSmove(tmpret20__1, atspre_g0int_gte_int(arg0, tmp21__1)) ;

ATSfunbody_end()
ATSreturn(tmpret20__1) ;
} /* end of [ATSLIB_056_prelude__gte_g0int_int__7__1] */

/*
build/bats_modules/env/src/lib.dats: 1598(line=70, offs=35) -- 1804(line=78, offs=4)
*/
/*
local: 
global: get_cstr$11$0(level=0)
local: 
global: 
*/
ATSextern()
atstype_boxed
build_057_bats_modules_057_env_057_src_057_lib_056_sats__get_cstr(atsrefarg0_type(atstkind_type(atstype_ptrk)) arg0, atsrefarg0_type(atstkind_type(atstype_ptrk)) arg1, atstkind_t0ype(atstype_int) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret24, atstype_boxed) ;
ATStmpdec(tmp25, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp26, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 1574(line=70, offs=11) -- 1804(line=78, offs=4)
*/
ATSINSflab(__patsflab_get_cstr):
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 1621(line=70, offs=58) -- 1804(line=78, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 1638(line=71, offs=14) -- 1747(line=74, offs=13)
*/
ATSINSmove(tmp25, ATSextfcall(_env_getenv, (ATSPMVcastfn(castvwtp1, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg0)), ATSPMVcastfn(castvwtp1, atstkind_type(atstype_ptrk), ATSPMVrefarg0(arg1)), arg2))) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 1757(line=76, offs=6) -- 1765(line=76, offs=14)
*/
ATSINSmove(tmp26, ATSLIB_056_prelude__gte_g0int_int__7__2(tmp25, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 1754(line=76, offs=3) -- 1800(line=77, offs=17)
*/
ATSif(
tmp26
) ATSthen() {
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 1771(line=76, offs=20) -- 1782(line=76, offs=31)
*/

/*
#LINCONSTATUS==0
*/
ATSINSmove_con1_beg()
ATSINSmove_con1_new(tmpret24, postiats_tysum_0) ;
#if(0)
ATSINSstore_con1_tag(tmpret24, 0) ;
#endif
ATSINSstore_con1_ofs(tmpret24, postiats_tysum_0, atslab__0, tmp25) ;
ATSINSmove_con1_end()
} ATSelse() {
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 1791(line=77, offs=8) -- 1800(line=77, offs=17)
*/

ATSINSmove_nil(tmpret24) ;

} /* ATSendif */
/*
emit_instr: loc0 = build/bats_modules/env/src/lib.dats: 1621(line=70, offs=58) -- 1804(line=78, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret24) ;
} /* end of [build_057_bats_modules_057_env_057_src_057_lib_056_sats__get_cstr] */

/*
$(PATSHOME)/prelude/DATS/integer.dats: 12178(line=630, offs=3) -- 12218(line=630, offs=43)
*/
/*
local: 
global: gte_g0int_int$7$2(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4811)
tmparg = S2Evar(tk(4811))
tmpsub = Some(tk(4811) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__gte_g0int_int__7__2(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret20__2, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp21__2, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12162(line=629, offs=1) -- 12218(line=630, offs=43)
*/
ATSINSflab(__patsflab_gte_g0int_int):
/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12205(line=630, offs=30) -- 12216(line=630, offs=41)
*/
ATSINSmove(tmp21__2, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = $(PATSHOME)/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 12187(line=630, offs=12) -- 12218(line=630, offs=43)
*/
ATSINSmove(tmpret20__2, atspre_g0int_gte_int(arg0, tmp21__2)) ;

ATSfunbody_end()
ATSreturn(tmpret20__2) ;
} /* end of [ATSLIB_056_prelude__gte_g0int_int__7__2] */

/*
** for initialization(dynloading)
*/
ATSextern()
atsvoid_t0ype
build_057_bats_modules_057_env_057_src_057_lib_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_ext(
build_057_bats_modules_057_env_057_src_057_lib_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
build_057_bats_modules_057_env_057_src_057_lib_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(build_057_bats_modules_057_env_057_src_057_lib_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/* ****** ****** */

/* end-of-compilation-unit */
