(* The wasm runtime's allocator, as Bats source (bats-lang/bats#241).

   A wasm binary's malloc and free are this module's text: the compiler
   writes it out (build/_bats_wasm_allocator.bats), checks it as it
   checks any module of an unsafe package (so the proven core, outside
   $UNSAFE, has the same rules: every recursion with a metric, no praxi,
   castfn or extern), runs patsopt on it, which proves its free lists,
   and links its object into the binary. The text is kept here as the
   runtime header and its C are kept in build.bats: line by line. *)

#include "share/atspre_staload.hats"

#use array as A
#use builder as B

staload "helpers.sats"

(* The allocator's source: the comment on what it is, and its prelude *)
fn put_allocator_head (b: !$B.builder_v >> $B.builder_v): void = let
  val () = bput_v(b, "(* The wasm runtime's allocator (bats-lang/bats#241).\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "   A block's header, the 8 bytes before it, holds its size. A freed\n")
  val () = bput_v(b, "   block is kept on a free list, its first word holding the next block.\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "   A request of at most 1 MiB (array's alloc bound) is served by a\n")
  val () = bput_v(b, "   bucket: one list per size from 32 bytes to 1 MiB, whose blocks serve\n")
  val () = bput_v(b, "   any request of at most that size.\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "   A larger request is a region: what an arena (array's arena_create)\n")
  val () = bput_v(b, "   takes, few of them and of a few fixed sizes. Its size is rounded up to\n")
  val () = bput_v(b, "   whole wasm pages (64 KiB), and a freed region is kept, in order of\n")
  val () = bput_v(b, "   size, for a request of exactly its size: no region serves a smaller\n")
  val () = bput_v(b, "   request, so regions are never split, merged or wasted, and a size\n")
  val () = bput_v(b, "   that is asked for again finds its region. wasm's memory cannot\n")
  val () = bput_v(b, "   shrink, so a region stays for its size.\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "   Every list is a view indexed by its length, which owns its blocks:\n")
  val () = bput_v(b, "   a cycle cannot be written, every walk ends by its length, and a block\n")
  val () = bput_v(b, "   is on one list at most. Only the C ABI the generated code calls\n")
  val () = bput_v(b, "   (malloc and free), the static storage of the lists' heads and the\n")
  val () = bput_v(b, "   bump of fresh memory are in $UNSAFE. *)\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "#include \"share/atspre_staload.hats\"\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "(* Nothing to run when the module loads *)\n")
  val () = bput_v(b, "#define ATS_DYNLOADFLAG 0\n")
  val () = bput_v(b, "\n")
in end

(* The allocator's source: the views of the free lists *)
fn put_allocator_statics (b: !$B.builder_v >> $B.builder_v): void = let
  val () = bput_v(b, "(* ============================================================\n")
  val () = bput_v(b, "   Statics\n")
  val () = bput_v(b, "   ============================================================ *)\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "(* The bucket b's size *)\n")
  val () = bput_v(b, "dataprop BUCKET(int, int) =\n")
  val () = bput_v(b, "  | BUCKET_32(0, 32) | BUCKET_128(1, 128) | BUCKET_512(2, 512)\n")
  val () = bput_v(b, "  | BUCKET_4K(3, 4096) | BUCKET_8K(4, 8192) | BUCKET_16K(5, 16384)\n")
  val () = bput_v(b, "  | BUCKET_64K(6, 65536) | BUCKET_256K(7, 262144) | BUCKET_1M(8, 1048576)\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "(* The bytes of a block of size bytes at l past its first word *)\n")
  val () = bput_v(b, "absview block_body_v(l:addr, size:int)\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "(* A block of size bytes at l: its header, its first word and the rest *)\n")
  val () = bput_v(b, "dataview block_v(addr, int) =\n")
  val () = bput_v(b, "  | {l:agz}{size:int}\n")
  val () = bput_v(b, "    block_parts(l, size) of (int(size) @ (l - 8), ptr @ l, block_body_v(l, size))\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "(* count free blocks from l, each of at least least bytes *)\n")
  val () = bput_v(b, "dataview bucket_v(addr, int, int) =\n")
  val () = bput_v(b, "  | {least:int} bucket_nil(null, least, 0) of ()\n")
  val () = bput_v(b, "  | {l:agz}{least,size:int | size >= least}{next:addr}{count:nat}\n")
  val () = bput_v(b, "    bucket_cons(l, least, count + 1) of\n")
  val () = bput_v(b, "      (int(size) @ (l - 8), ptr(next) @ l, block_body_v(l, size),\n")
  val () = bput_v(b, "       bucket_v(next, least, count))\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "(* count free regions from l, in order of size, each of at least least\n")
  val () = bput_v(b, "   bytes *)\n")
  val () = bput_v(b, "dataview regions_v(addr, int, int) =\n")
  val () = bput_v(b, "  | {least:int} regions_nil(null, least, 0) of ()\n")
  val () = bput_v(b, "  | {l:agz}{least,size:int | size >= least}{next:addr}{count:nat}\n")
  val () = bput_v(b, "    regions_cons(l, least, count + 1) of\n")
  val () = bput_v(b, "      (int(size) @ (l - 8), ptr(next) @ l, block_body_v(l, size),\n")
  val () = bput_v(b, "       regions_v(next, size, count))\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "(* The heads of the buckets from bucket b on, from l: each head and the\n")
  val () = bput_v(b, "   list it starts *)\n")
  val () = bput_v(b, "dataview heads_v(addr, int) =\n")
  val () = bput_v(b, "  | {l:addr} heads_end(l, 9) of ()\n")
  val () = bput_v(b, "  | {l:addr}{b:nat | b < 9}{size:int}{head:addr}{count:nat}\n")
  val () = bput_v(b, "    heads_cons(l, b) of\n")
  val () = bput_v(b, "      (BUCKET(b, size), ptr(head) @ l, bucket_v(head, size, count),\n")
  val () = bput_v(b, "       heads_v(l + 4, b + 1))\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "(* What a list gives for a request of n bytes: nothing, or a block of at\n")
  val () = bput_v(b, "   least n bytes *)\n")
  val () = bput_v(b, "dataview taken_v(addr, int) =\n")
  val () = bput_v(b, "  | {n:int} taken_none(null, n) of ()\n")
  val () = bput_v(b, "  | {l:agz}{n,size:int | size >= n} taken_block(l, n) of block_v(l, size)\n")
  val () = bput_v(b, "\n")
in end

(* The allocator's source: the lemmas *)
fn put_allocator_lemmas (b: !$B.builder_v >> $B.builder_v): void = let
  val () = bput_v(b, "(* ============================================================\n")
  val () = bput_v(b, "   Lemmas\n")
  val () = bput_v(b, "   ============================================================ *)\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "prfn bucket_same {b:int}{s1,s2:int}\n")
  val () = bput_v(b, "  (p1: BUCKET(b, s1), p2: BUCKET(b, s2)): [s1 == s2] void =\n")
  val () = bput_v(b, "  case+ p1 of\n")
  val () = bput_v(b, "  | BUCKET_32() => let prval BUCKET_32() = p2 in end\n")
  val () = bput_v(b, "  | BUCKET_128() => let prval BUCKET_128() = p2 in end\n")
  val () = bput_v(b, "  | BUCKET_512() => let prval BUCKET_512() = p2 in end\n")
  val () = bput_v(b, "  | BUCKET_4K() => let prval BUCKET_4K() = p2 in end\n")
  val () = bput_v(b, "  | BUCKET_8K() => let prval BUCKET_8K() = p2 in end\n")
  val () = bput_v(b, "  | BUCKET_16K() => let prval BUCKET_16K() = p2 in end\n")
  val () = bput_v(b, "  | BUCKET_64K() => let prval BUCKET_64K() = p2 in end\n")
  val () = bput_v(b, "  | BUCKET_256K() => let prval BUCKET_256K() = p2 in end\n")
  val () = bput_v(b, "  | BUCKET_1M() => let prval BUCKET_1M() = p2 in end\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "(* A list of blocks of at least least bytes holds blocks of at least\n")
  val () = bput_v(b, "   fewer bytes *)\n")
  val () = bput_v(b, "prfn regions_lower {l:addr}{least,fewer:int | fewer <= least}{count:nat}\n")
  val () = bput_v(b, "  (list: regions_v(l, least, count)): regions_v(l, fewer, count) =\n")
  val () = bput_v(b, "  case+ list of\n")
  val () = bput_v(b, "  | regions_nil() => regions_nil()\n")
  val () = bput_v(b, "  | regions_cons(header, word, body, rest) => regions_cons(header, word, body, rest)\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "prfn taken_lower {l:addr}{n,fewer:int | fewer <= n}\n")
  val () = bput_v(b, "  (taken: taken_v(l, n)): taken_v(l, fewer) =\n")
  val () = bput_v(b, "  case+ taken of\n")
  val () = bput_v(b, "  | taken_none() => taken_none()\n")
  val () = bput_v(b, "  | taken_block(block) => taken_block(block)\n")
  val () = bput_v(b, "\n")
in end

(* The allocator's source: the buckets *)
fn put_allocator_buckets (b: !$B.builder_v >> $B.builder_v): void = let
  val () = bput_v(b, "(* ============================================================\n")
  val () = bput_v(b, "   Buckets\n")
  val () = bput_v(b, "   ============================================================ *)\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "(* The bucket for a request of n bytes: the smallest of at least n *)\n")
  val () = bput_v(b, "fn bucket_for {n:pos | n <= 1048576} (n: int n)\n")
  val () = bput_v(b, "  : [b:nat | b < 9][size:int | size >= n] (BUCKET(b, size) | @(int b, int size)) =\n")
  val () = bput_v(b, "  if n <= 32 then (BUCKET_32() | @(0, 32))\n")
  val () = bput_v(b, "  else if n <= 128 then (BUCKET_128() | @(1, 128))\n")
  val () = bput_v(b, "  else if n <= 512 then (BUCKET_512() | @(2, 512))\n")
  val () = bput_v(b, "  else if n <= 4096 then (BUCKET_4K() | @(3, 4096))\n")
  val () = bput_v(b, "  else if n <= 8192 then (BUCKET_8K() | @(4, 8192))\n")
  val () = bput_v(b, "  else if n <= 16384 then (BUCKET_16K() | @(5, 16384))\n")
  val () = bput_v(b, "  else if n <= 65536 then (BUCKET_64K() | @(6, 65536))\n")
  val () = bput_v(b, "  else if n <= 262144 then (BUCKET_256K() | @(7, 262144))\n")
  val () = bput_v(b, "  else (BUCKET_1M() | @(8, 1048576))\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "(* The bucket for a freed block of size bytes: the largest of at most\n")
  val () = bput_v(b, "   size, whose requests it serves *)\n")
  val () = bput_v(b, "fn bucket_of {size:int | size >= 32; size <= 1048576} (size: int size)\n")
  val () = bput_v(b, "  : [b:nat | b < 9][least:int | least <= size] (BUCKET(b, least) | int b) =\n")
  val () = bput_v(b, "  if size < 128 then (BUCKET_32() | 0)\n")
  val () = bput_v(b, "  else if size < 512 then (BUCKET_128() | 1)\n")
  val () = bput_v(b, "  else if size < 4096 then (BUCKET_512() | 2)\n")
  val () = bput_v(b, "  else if size < 8192 then (BUCKET_4K() | 3)\n")
  val () = bput_v(b, "  else if size < 16384 then (BUCKET_8K() | 4)\n")
  val () = bput_v(b, "  else if size < 65536 then (BUCKET_16K() | 5)\n")
  val () = bput_v(b, "  else if size < 262144 then (BUCKET_64K() | 6)\n")
  val () = bput_v(b, "  else if size < 1048576 then (BUCKET_256K() | 7)\n")
  val () = bput_v(b, "  else (BUCKET_1M() | 8)\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "(* The first block of the list whose head is at link, taken off it *)\n")
  val () = bput_v(b, "fn bucket_pop {link,head:addr}{least:int}{count:nat}\n")
  val () = bput_v(b, "  (pf_head: !ptr(head) @ link >> ptr(rest) @ link,\n")
  val () = bput_v(b, "   pf_list: !bucket_v(head, least, count) >> bucket_v(rest, least, left)\n")
  val () = bput_v(b, "  | link: ptr link): #[rest:addr; left:nat] [l:addr] (taken_v(l, least) | ptr l) = let\n")
  val () = bput_v(b, "  val head = !link\n")
  val () = bput_v(b, "in\n")
  val () = bput_v(b, "  if ptr1_isnot_null(head) then let\n")
  val () = bput_v(b, "    prval bucket_cons(header, word, body, tail) = pf_list\n")
  val () = bput_v(b, "    val next = !head\n")
  val () = bput_v(b, "    val () = !link := next\n")
  val () = bput_v(b, "    prval () = pf_list := tail\n")
  val () = bput_v(b, "  in (taken_block(block_parts(header, word, body)) | head) end\n")
  val () = bput_v(b, "  else (taken_none() | the_null_ptr)\n")
  val () = bput_v(b, "end\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "(* The block at l put first on the list whose head is at link *)\n")
  val () = bput_v(b, "fn bucket_push {link,head:addr}{least:int}{count:nat}{l:agz}{size:int | size >= least}\n")
  val () = bput_v(b, "  (pf_head: !ptr(head) @ link >> ptr(l) @ link,\n")
  val () = bput_v(b, "   pf_list: !bucket_v(head, least, count) >> bucket_v(l, least, count + 1),\n")
  val () = bput_v(b, "   block: block_v(l, size)\n")
  val () = bput_v(b, "  | link: ptr link, p: ptr l): void = let\n")
  val () = bput_v(b, "  prval block_parts(header, word, body) = block\n")
  val () = bput_v(b, "  val head = !link\n")
  val () = bput_v(b, "  val () = !p := head\n")
  val () = bput_v(b, "  val () = !link := p\n")
  val () = bput_v(b, "  prval () = pf_list := bucket_cons(header, word, body, pf_list)\n")
  val () = bput_v(b, "in end\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "(* A block of bucket target's size, taken off its list, walking the\n")
  val () = bput_v(b, "   heads from bucket b's, at heads *)\n")
  val () = bput_v(b, "fun heads_pop {heads:addr}{b:nat}{target:nat | b <= target; target < 9}\n")
  val () = bput_v(b, "  {size:int} .<target - b>.\n")
  val () = bput_v(b, "  (pf_heads: !heads_v(heads, b), pf_size: BUCKET(target, size)\n")
  val () = bput_v(b, "  | heads: ptr heads, b: int b, target: int target): [l:addr] (taken_v(l, size) | ptr l) = let\n")
  val () = bput_v(b, "  prval heads_cons(pf_bucket, pf_head, pf_list, pf_rest) = pf_heads\n")
  val () = bput_v(b, "in\n")
  val () = bput_v(b, "  if b = target then let\n")
  val () = bput_v(b, "    prval () = bucket_same(pf_bucket, pf_size)\n")
  val () = bput_v(b, "    val (taken | p) = bucket_pop(pf_head, pf_list | heads)\n")
  val () = bput_v(b, "    prval () = pf_heads := heads_cons(pf_bucket, pf_head, pf_list, pf_rest)\n")
  val () = bput_v(b, "  in (taken | p) end\n")
  val () = bput_v(b, "  else let\n")
  val () = bput_v(b, "    val (taken | p) = heads_pop(pf_rest, pf_size | add_ptr1_bsz(heads, i2sz(4)), b + 1, target)\n")
  val () = bput_v(b, "    prval () = pf_heads := heads_cons(pf_bucket, pf_head, pf_list, pf_rest)\n")
  val () = bput_v(b, "  in (taken | p) end\n")
  val () = bput_v(b, "end\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "(* The block at l put on bucket target's list, walking the heads from\n")
  val () = bput_v(b, "   bucket b's, at heads *)\n")
  val () = bput_v(b, "fun heads_push {heads:addr}{b:nat}{target:nat | b <= target; target < 9}\n")
  val () = bput_v(b, "  {least:int}{l:agz}{size:int | size >= least} .<target - b>.\n")
  val () = bput_v(b, "  (pf_heads: !heads_v(heads, b), pf_least: BUCKET(target, least), block: block_v(l, size)\n")
  val () = bput_v(b, "  | heads: ptr heads, b: int b, target: int target, p: ptr l): void = let\n")
  val () = bput_v(b, "  prval heads_cons(pf_bucket, pf_head, pf_list, pf_rest) = pf_heads\n")
  val () = bput_v(b, "in\n")
  val () = bput_v(b, "  if b = target then let\n")
  val () = bput_v(b, "    prval () = bucket_same(pf_bucket, pf_least)\n")
  val () = bput_v(b, "    val () = bucket_push(pf_head, pf_list, block | heads, p)\n")
  val () = bput_v(b, "    prval () = pf_heads := heads_cons(pf_bucket, pf_head, pf_list, pf_rest)\n")
  val () = bput_v(b, "  in end\n")
  val () = bput_v(b, "  else let\n")
  val () = bput_v(b, "    val () = heads_push(pf_rest, pf_least, block | add_ptr1_bsz(heads, i2sz(4)), b + 1, target, p)\n")
  val () = bput_v(b, "    prval () = pf_heads := heads_cons(pf_bucket, pf_head, pf_list, pf_rest)\n")
  val () = bput_v(b, "  in end\n")
  val () = bput_v(b, "end\n")
  val () = bput_v(b, "\n")
in end

(* The allocator's source: the regions *)
fn put_allocator_large (b: !$B.builder_v >> $B.builder_v): void = let
  val () = bput_v(b, "(* ============================================================\n")
  val () = bput_v(b, "   The regions\n")
  val () = bput_v(b, "   ============================================================ *)\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "(* The size in the header of the block at l *)\n")
  val () = bput_v(b, "fn header_read {l:agz}{size:int} (pf: !int(size) @ (l - 8) | p: ptr l): int size =\n")
  val () = bput_v(b, "  !(sub_ptr1_bsz(p, i2sz(8)))\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "(* n bytes rounded up to whole wasm pages *)\n")
  val () = bput_v(b, "fn whole_pages {n:pos} (n: int n): [size:int | size >= n] int size = let\n")
  val () = bput_v(b, "  val (_ | past) = g1int_nmod2(n, 65536)\n")
  val () = bput_v(b, "in\n")
  val () = bput_v(b, "  if past = 0 then n else n + (65536 - past)\n")
  val () = bput_v(b, "end\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "(* What the regions give for a request of n bytes: nothing, or a region\n")
  val () = bput_v(b, "   of exactly n bytes *)\n")
  val () = bput_v(b, "dataview region_v(addr, int) =\n")
  val () = bput_v(b, "  | {n:int} region_none(null, n) of ()\n")
  val () = bput_v(b, "  | {l:agz}{n:int} region_block(l, n) of block_v(l, n)\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "prfn region_taken {l:addr}{n:int} (region: region_v(l, n)): taken_v(l, n) =\n")
  val () = bput_v(b, "  case+ region of\n")
  val () = bput_v(b, "  | region_none() => taken_none()\n")
  val () = bput_v(b, "  | region_block(block) => taken_block(block)\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "(* The region of exactly n bytes on the list whose head is at link, taken\n")
  val () = bput_v(b, "   off it: the walk passes the smaller regions and ends at the list's\n")
  val () = bput_v(b, "   end, by its length *)\n")
  val () = bput_v(b, "fun region_take {link,head:addr}{least:int}{count:nat}{n:pos} .<count>.\n")
  val () = bput_v(b, "  (pf_head: !ptr(head) @ link >> ptr(rest) @ link,\n")
  val () = bput_v(b, "   pf_list: !regions_v(head, least, count) >> regions_v(rest, least, left)\n")
  val () = bput_v(b, "  | link: ptr link, n: int n): #[rest:addr; left:nat] [l:addr] (region_v(l, n) | ptr l) = let\n")
  val () = bput_v(b, "  val head = !link\n")
  val () = bput_v(b, "in\n")
  val () = bput_v(b, "  if ptr1_isnot_null(head) then let\n")
  val () = bput_v(b, "    prval regions_cons(header, word, body, tail) = pf_list\n")
  val () = bput_v(b, "    val size = header_read(header | head)\n")
  val () = bput_v(b, "  in\n")
  val () = bput_v(b, "    if size < n then let\n")
  val () = bput_v(b, "      val (region | p) = region_take(word, tail | head, n)\n")
  val () = bput_v(b, "      prval () = pf_list := regions_cons(header, word, body, tail)\n")
  val () = bput_v(b, "    in (region | p) end\n")
  val () = bput_v(b, "    else if size = n then let\n")
  val () = bput_v(b, "      val next = !head\n")
  val () = bput_v(b, "      val () = !link := next\n")
  val () = bput_v(b, "      prval () = pf_list := regions_lower(tail)\n")
  val () = bput_v(b, "    in (region_block(block_parts(header, word, body)) | head) end\n")
  val () = bput_v(b, "    else let\n")
  val () = bput_v(b, "      prval () = pf_list := regions_cons(header, word, body, tail)\n")
  val () = bput_v(b, "    in (region_none() | the_null_ptr) end\n")
  val () = bput_v(b, "  end\n")
  val () = bput_v(b, "  else (region_none() | the_null_ptr)\n")
  val () = bput_v(b, "end\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "(* The block at l, of size bytes, put on the list whose head is at link\n")
  val () = bput_v(b, "   before its first block of at least size bytes *)\n")
  val () = bput_v(b, "fun region_insert {link,head:addr}{least:int}{count:nat}{l:agz}{size:int | size >= least} .<count>.\n")
  val () = bput_v(b, "  (pf_head: !ptr(head) @ link >> ptr(first) @ link,\n")
  val () = bput_v(b, "   pf_list: !regions_v(head, least, count) >> regions_v(first, least, count + 1),\n")
  val () = bput_v(b, "   block: block_v(l, size)\n")
  val () = bput_v(b, "  | link: ptr link, p: ptr l, size: int size): #[first:addr] void = let\n")
  val () = bput_v(b, "  val head = !link\n")
  val () = bput_v(b, "in\n")
  val () = bput_v(b, "  if ptr1_isnot_null(head) then let\n")
  val () = bput_v(b, "    prval regions_cons(header, word, body, tail) = pf_list\n")
  val () = bput_v(b, "    val here = header_read(header | head)\n")
  val () = bput_v(b, "  in\n")
  val () = bput_v(b, "    if here < size then let\n")
  val () = bput_v(b, "      val () = region_insert(word, tail, block | head, p, size)\n")
  val () = bput_v(b, "      prval () = pf_list := regions_cons(header, word, body, tail)\n")
  val () = bput_v(b, "    in end\n")
  val () = bput_v(b, "    else let\n")
  val () = bput_v(b, "      prval block_parts(new_header, new_word, new_body) = block\n")
  val () = bput_v(b, "      val () = !p := head\n")
  val () = bput_v(b, "      val () = !link := p\n")
  val () = bput_v(b, "      prval () = pf_list := regions_cons(new_header, new_word, new_body,\n")
  val () = bput_v(b, "        regions_cons(header, word, body, tail))\n")
  val () = bput_v(b, "    in end\n")
  val () = bput_v(b, "  end\n")
  val () = bput_v(b, "  else let\n")
  val () = bput_v(b, "    prval regions_nil() = pf_list\n")
  val () = bput_v(b, "    prval block_parts(new_header, new_word, new_body) = block\n")
  val () = bput_v(b, "    val () = !p := the_null_ptr\n")
  val () = bput_v(b, "    val () = !link := p\n")
  val () = bput_v(b, "    prval () = pf_list := regions_cons(new_header, new_word, new_body, regions_nil())\n")
  val () = bput_v(b, "  in end\n")
  val () = bput_v(b, "end\n")
  val () = bput_v(b, "\n")
in end

(* The allocator's source: the C ABI malloc and free, the only $UNSAFE *)
fn put_allocator_boundary (b: !$B.builder_v >> $B.builder_v): void = let
  val () = bput_v(b, "(* ============================================================\n")
  val () = bput_v(b, "   The boundary: the C ABI the generated code calls\n")
  val () = bput_v(b, "   ============================================================ *)\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "$UNSAFE begin\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "%{^\n")
  val () = bput_v(b, "/* The heads of the buckets' lists, and of the regions' list */\n")
  val () = bput_v(b, "static void *bats_alloc_heads[9] = {0, 0, 0, 0, 0, 0, 0, 0, 0};\n")
  val () = bput_v(b, "static void *bats_alloc_regions = 0;\n")
  val () = bput_v(b, "#define bats_alloc_heads_take() ((void*)bats_alloc_heads)\n")
  val () = bput_v(b, "#define bats_alloc_regions_take() ((void*)&bats_alloc_regions)\n")
  val () = bput_v(b, "#define bats_alloc_zero(p, size) ((void)memset((p), 0, (unsigned int)(size)))\n")
  val () = bput_v(b, "/* A block of size bytes past an 8-byte header that holds size, from\n")
  val () = bput_v(b, "   the top of the heap, which grows by whole pages when it must; 0 when\n")
  val () = bput_v(b, "   it cannot */\n")
  val () = bput_v(b, "extern unsigned char __heap_base;\n")
  val () = bput_v(b, "static unsigned char *bats_alloc_top = &__heap_base;\n")
  val () = bput_v(b, "static void *bats_alloc_bump(int size) {\n")
  val () = bput_v(b, "  unsigned long start = ((unsigned long)bats_alloc_top + 7UL) & ~7UL;\n")
  val () = bput_v(b, "  unsigned long end = start + 8UL + (unsigned long)size;\n")
  val () = bput_v(b, "  unsigned long limit = (unsigned long)__builtin_wasm_memory_size(0) * 65536UL;\n")
  val () = bput_v(b, "  if (end > limit) {\n")
  val () = bput_v(b, "    unsigned long pages = (end - limit + 65535UL) / 65536UL;\n")
  val () = bput_v(b, "    if (__builtin_wasm_memory_grow(0, pages) == (unsigned long)(-1)) return (void*)0;\n")
  val () = bput_v(b, "  }\n")
  val () = bput_v(b, "  *(int*)start = size;\n")
  val () = bput_v(b, "  bats_alloc_top = (unsigned char*)end;\n")
  val () = bput_v(b, "  return (void*)(start + 8UL);\n")
  val () = bput_v(b, "}\n")
  val () = bput_v(b, "%}\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "(* The lists' heads are in static storage. wasm runs one call at a time,\n")
  val () = bput_v(b, "   and malloc and free call neither each other nor themselves, so each\n")
  val () = bput_v(b, "   call takes the heads' views once and gives them back once *)\n")
  val () = bput_v(b, "extern fun heads_take (): [l:agz] (heads_v(l, 0) | ptr l) = \"mac#bats_alloc_heads_take\"\n")
  val () = bput_v(b, "extern praxi heads_give {l:addr} (heads: heads_v(l, 0)): void\n")
  val () = bput_v(b, "extern fun regions_take ()\n")
  val () = bput_v(b, "  : [link:agz][head:addr][count:nat] (ptr(head) @ link, regions_v(head, 0, count) | ptr link)\n")
  val () = bput_v(b, "  = \"mac#bats_alloc_regions_take\"\n")
  val () = bput_v(b, "extern praxi regions_give {link,head:addr}{count:nat}\n")
  val () = bput_v(b, "  (pf_head: ptr(head) @ link, pf_list: regions_v(head, 0, count)): void\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "(* A block malloc hands to the generated code leaves the allocator's\n")
  val () = bput_v(b, "   views; one the generated code frees, which malloc gave it, comes back\n")
  val () = bput_v(b, "   to them (the generated code frees what it allocated once: its values\n")
  val () = bput_v(b, "   are linear) *)\n")
  val () = bput_v(b, "extern praxi block_give {l:addr}{size:int} (block: block_v(l, size)): void\n")
  val () = bput_v(b, "extern praxi block_return {l:agz} (): [size:nat] block_v(l, size)\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "extern fun bump {size:pos} (size: int size): [l:addr] ptr l = \"mac#bats_alloc_bump\"\n")
  val () = bput_v(b, "extern fun zero {l:addr} (p: ptr l, size: int): void = \"mac#bats_alloc_zero\"\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "(* The block a list gave, zeroed, or a block bumped from the heap when\n")
  val () = bput_v(b, "   it gave none *)\n")
  val () = bput_v(b, "fn deliver {l:addr}{n:pos} (taken: taken_v(l, n) | p: ptr l, n: int n): ptr =\n")
  val () = bput_v(b, "  if ptr1_isnot_null(p) then let\n")
  val () = bput_v(b, "    prval taken_block(block) = taken\n")
  val () = bput_v(b, "    prval block_parts(header, word, body) = block\n")
  val () = bput_v(b, "    val size = header_read(header | p)\n")
  val () = bput_v(b, "    val () = zero(p, size)\n")
  val () = bput_v(b, "    prval () = block_give(block_parts(header, word, body))\n")
  val () = bput_v(b, "  in p end\n")
  val () = bput_v(b, "  else let\n")
  val () = bput_v(b, "    prval taken_none() = taken\n")
  val () = bput_v(b, "    val q = bump(n)\n")
  val () = bput_v(b, "  in\n")
  val () = bput_v(b, "    if ptr1_isnot_null(q) then let val () = zero(q, n) in q end\n")
  val () = bput_v(b, "    else q\n")
  val () = bput_v(b, "  end\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "extern fun malloc {n:int} (size: int n): ptr = \"ext#malloc\"\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "implement malloc {n} (size) = let\n")
  val () = bput_v(b, "  val n = (if size <= 0 then 1 else size): [m:pos] int m\n")
  val () = bput_v(b, "in\n")
  val () = bput_v(b, "  if n <= 1048576 then let\n")
  val () = bput_v(b, "    val (pf_size | @(b, bucket_size)) = bucket_for(n)\n")
  val () = bput_v(b, "    val (pf_heads | heads) = heads_take()\n")
  val () = bput_v(b, "    val (taken | p) = heads_pop(pf_heads, pf_size | heads, 0, b)\n")
  val () = bput_v(b, "    prval () = heads_give(pf_heads)\n")
  val () = bput_v(b, "  in deliver(taken | p, bucket_size) end\n")
  val () = bput_v(b, "  else let\n")
  val () = bput_v(b, "    val size = whole_pages(n)\n")
  val () = bput_v(b, "    val (pf_head, pf_list | link) = regions_take()\n")
  val () = bput_v(b, "    val (region | p) = region_take(pf_head, pf_list | link, size)\n")
  val () = bput_v(b, "    prval () = regions_give(pf_head, pf_list)\n")
  val () = bput_v(b, "  in deliver(region_taken(region) | p, size) end\n")
  val () = bput_v(b, "end\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "fn free_region {l:agz}{size:nat} (block: block_v(l, size) | p: ptr l, size: int size): void = let\n")
  val () = bput_v(b, "  val (pf_head, pf_list | link) = regions_take()\n")
  val () = bput_v(b, "  val () = region_insert(pf_head, pf_list, block | link, p, size)\n")
  val () = bput_v(b, "  prval () = regions_give(pf_head, pf_list)\n")
  val () = bput_v(b, "in end\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "extern fun free {l:addr} (p: ptr l): void = \"ext#free\"\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "implement free {l} (p) =\n")
  val () = bput_v(b, "  if ptr1_isnot_null(p) then let\n")
  val () = bput_v(b, "    prval block_parts(header, word, body) = block_return{l}()\n")
  val () = bput_v(b, "    val size = header_read(header | p)\n")
  val () = bput_v(b, "    prval block = block_parts(header, word, body)\n")
  val () = bput_v(b, "  in\n")
  val () = bput_v(b, "    if size < 32 then free_region(block | p, size)\n")
  val () = bput_v(b, "    else if size > 1048576 then free_region(block | p, size)\n")
  val () = bput_v(b, "    else let\n")
  val () = bput_v(b, "      val (pf_least | b) = bucket_of(size)\n")
  val () = bput_v(b, "      val (pf_heads | heads) = heads_take()\n")
  val () = bput_v(b, "      val () = heads_push(pf_heads, pf_least, block | heads, 0, b, p)\n")
  val () = bput_v(b, "      prval () = heads_give(pf_heads)\n")
  val () = bput_v(b, "    in end\n")
  val () = bput_v(b, "  end\n")
  val () = bput_v(b, "  else ()\n")
  val () = bput_v(b, "\n")
  val () = bput_v(b, "end\n")
in end

(* Writes the allocator's source to build/_bats_wasm_allocator.bats;
   0 when it is written *)
#pub fn write_wasm_allocator (): int

implement write_wasm_allocator () = let
  var b : $B.builder_v = $B.create()
  val () = put_allocator_head(b)
  val () = put_allocator_statics(b)
  val () = put_allocator_lemmas(b)
  val () = put_allocator_buckets(b)
  val () = put_allocator_large(b)
  val () = put_allocator_boundary(b)
  val p = str_to_path_arr("build/_bats_wasm_allocator.bats")
  val @(fz_p, bv_p) = $A.freeze<byte>(p)
  val rc = write_file_from_builder(bv_p, 524288, b)
  val () = $A.drop<byte>(fz_p, bv_p)
  val () = $A.free<byte>($A.thaw<byte>(fz_p))
in rc end
